
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- LibTemplate: Data Grid -->
<span id="LibTemplateGrid">
<?php include_once("lib-template-grid.phtml");?>
</span>
<!-- [End] LibTemplate: Data Grid -->

<!-- LibTemplate: Modal Form -->
<?php include_once("lib-template-modal.phtml");?>
<!-- [End] LibTemplate: Modal Form -->


<script type="text/javascript">

	var theme = "source/lib-template";

	$(document).ready(function() {
		$("#navLibTemplate").addClass("active");
		searchHandler["srch-libTemplate"] = {
				action: theme + "/lib-template-grid",
				container: "LibTemplateGrid"
		};
    searchStack["srch-libTemplate"] = wrapFunction(search, this, ["srch-libTemplate"]);
	});

	function addLibTemplate(id) {
		//$("#libTemplateModalHeading").html("Add New Lib Template");
		mode = "create";
		clearForm("libTemplate", "modalLibTemplate");
	}

	function editLibTemplate(id) {
		//$("#libTemplateModalHeading").html("Edit Lib Template");
		mode = "update";
		populateForm("libTemplate", "lib_template", libTemplateData[id], "modalLibTemplate");
	}

</script>