<!-- LibTemplate: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibTemplate">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libTemplateModalHeading">Edit Lib Template</h3>
	  </div>
		<form id="libTemplateForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libTemplate_name"><b>Name *</b></label>
						<input id="libTemplate_name" name="name" type="text"
							form-id="libTemplate" class="span12 required" maxlength="50">
					</div>
		  		<div class="control-group">
		    		<label for="libTemplate_subject"><b>Subject *</b></label>
						<input id="libTemplate_subject" name="subject" type="text"
							form-id="libTemplate" class="span12 required" maxlength="100">
					</div>
		  		<div class="control-group">
			  		<label for="libTemplate_tags"><b>Tags</b></label>
						<textarea id="libTemplate_tags" name="tags" rows="5"
							form-id="libTemplate" class="span12 " maxlength="65535"></textarea>
					</div>
		  		<div class="control-group">
			  		<label for="libTemplate_email_template"><b>Email Template</b></label>
						<textarea id="libTemplate_email_template" name="email_template" rows="5"
							form-id="libTemplate" class="span12 " maxlength="65535"></textarea>
					</div>
		  		<div class="control-group">
			  		<label for="libTemplate_sms_template"><b>Sms Template</b></label>
						<textarea id="libTemplate_sms_template" name="sms_template" rows="5"
							form-id="libTemplate" class="span12 " maxlength="65535"></textarea>
					</div>
				<input type="hidden" id="libTemplate_id" name="id" form-id="libTemplate">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibTemplate: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libTemplateForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libTemplate", "libTemplate", "api/data/" + mode,
			  	"LibTemplateGrid", theme + "/lib-template-grid",
					false, true, false, {});
		  }
		});
	});
</script>