<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibTemplateGrid",
		"lib-template-grid",
		$this->result["LibTemplate"]["Paging"]["CurrentPage"],
		$this->result["LibTemplate"]["Paging"]["TotalPages"],
		$this->result["LibTemplate"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibTemplate"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_template.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libTemplate', 'lib_template.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_template.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libTemplate', 'lib_template.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Subject</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_template.subject" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libTemplate', 'lib_template.subject', 'asc');"></i>
							<i class="icon-<?php echo "lib_template.subject" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libTemplate', 'lib_template.subject', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibTemplate();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libTemplate_lib_template.name" type="text" class="span12 srch-libTemplate"
						value="<?php echo isset($this->result['LibTemplate']['Search']['lib_template.name']) ? $this->result['LibTemplate']['Search']['lib_template.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libTemplate_lib_template.subject" type="text" class="span12 srch-libTemplate"
						value="<?php echo isset($this->result['LibTemplate']['Search']['lib_template.subject']) ? $this->result['LibTemplate']['Search']['lib_template.subject'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libTemplate');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibTemplate"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["subject"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibTemplate(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibTemplate"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="2">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libTemplateData = <?php echo Zend_Json::encode($this->data["LibTemplate"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libTemplate"]();
		});
		$(".srch-libTemplate").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libTemplate"]();
		    }
		});
	});
	
</script>