<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AssetSubTypeGrid",
		"asset-sub-type-grid",
		$this->result["AssetSubType"]["Paging"]["CurrentPage"],
		$this->result["AssetSubType"]["Paging"]["TotalPages"],
		$this->result["AssetSubType"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["AssetSubType"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Asset Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_type.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubType', 'asset_sub_type.name', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_type.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubType', 'asset_sub_type.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_type.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubType', 'asset_sub_type.name', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_type.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubType', 'asset_sub_type.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_type.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubType', 'asset_sub_type.created', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_type.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubType', 'asset_sub_type.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_type.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubType', 'asset_sub_type.updated', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_type.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubType', 'asset_sub_type.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAssetSubType();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubType_asset_type.name" type="text" class="span12 srch-assetSubType"
						value="<?php echo isset($this->result['AssetSubType']['Search']['asset_type.name']) ? $this->result['AssetSubType']['Search']['asset_type.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubType_asset_sub_type.name" type="text" class="span12 srch-assetSubType"
						value="<?php echo isset($this->result['AssetSubType']['Search']['asset_sub_type.name']) ? $this->result['AssetSubType']['Search']['asset_sub_type.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubType_asset_sub_type.created" type="text" class="span12 srch-assetSubType"
						value="<?php echo isset($this->result['AssetSubType']['Search']['asset_sub_type.created']) ? $this->result['AssetSubType']['Search']['asset_sub_type.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubType_asset_sub_type.updated" type="text" class="span12 srch-assetSubType"
						value="<?php echo isset($this->result['AssetSubType']['Search']['asset_sub_type.updated']) ? $this->result['AssetSubType']['Search']['asset_sub_type.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-assetSubType');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["AssetSubType"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["asset_type_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAssetSubType(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["AssetSubType"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var assetSubTypeData = <?php echo Zend_Json::encode($this->data["AssetSubType"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-assetSubType"]();
		});
		$(".srch-assetSubType").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-assetSubType"]();
		    }
		});
	});
	
</script>