<!-- AssetSubType: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalAssetSubType">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="assetSubTypeModalHeading">Edit Asset Sub Type</h3>
	  </div>
		<form id="assetSubTypeForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="assetSubType_asset_type_id"><b>Asset Type *</b></label>
						<select id="assetSubType_asset_type_id" name="asset_type_id"
							form-id="assetSubType" class="span12 required" >
							<option value="">-- Select Asset Type * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listAssetType"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="assetSubType_name"><b>Name *</b></label>
						<input id="assetSubType_name" name="name" type="text"
							form-id="assetSubType" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="assetSubType_id" name="id" form-id="assetSubType">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] AssetSubType: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#assetSubTypeForm").validate({
		  submitHandler: function(form) {
			  doUpdate("assetSubType", "assetSubType", "api/data/" + mode,
			  	"AssetSubTypeGrid", theme + "/asset-sub-type-grid",
					false, true, false, {});
		  }
		});
	});
</script>