
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- AssetSubType: Data Grid -->
<span id="AssetSubTypeGrid">
<?php include_once("asset-sub-type-grid.phtml");?>
</span>
<!-- [End] AssetSubType: Data Grid -->

<!-- AssetSubType: Modal Form -->
<?php include_once("asset-sub-type-modal.phtml");?>
<!-- [End] AssetSubType: Modal Form -->


<script type="text/javascript">

	var theme = "source/asset-sub-type";

	$(document).ready(function() {
		$("#navAssetSubType").addClass("active");
		searchHandler["srch-assetSubType"] = {
				action: theme + "/asset-sub-type-grid",
				container: "AssetSubTypeGrid"
		};
    searchStack["srch-assetSubType"] = wrapFunction(search, this, ["srch-assetSubType"]);
	});

	function addAssetSubType(id) {
		//$("#assetSubTypeModalHeading").html("Add New Asset Sub Type");
		mode = "create";
		clearForm("assetSubType", "modalAssetSubType");
	}

	function editAssetSubType(id) {
		//$("#assetSubTypeModalHeading").html("Edit Asset Sub Type");
		mode = "update";
		populateForm("assetSubType", "asset_sub_type", assetSubTypeData[id], "modalAssetSubType");
	}

</script>