<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibAddressGrid",
		"lib-address-grid",
		$this->result["LibAddress"]["Paging"]["CurrentPage"],
		$this->result["LibAddress"]["Paging"]["TotalPages"],
		$this->result["LibAddress"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibAddress"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_address.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAddress', 'lib_address.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_address.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAddress', 'lib_address.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Lib City</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_address.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAddress', 'lib_address.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_address.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAddress', 'lib_address.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Address</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_address.address" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAddress', 'lib_address.address', 'asc');"></i>
							<i class="icon-<?php echo "lib_address.address" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAddress', 'lib_address.address', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Postal Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_address.postal_code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAddress', 'lib_address.postal_code', 'asc');"></i>
							<i class="icon-<?php echo "lib_address.postal_code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAddress', 'lib_address.postal_code', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Latitude</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_address.latitude" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAddress', 'lib_address.latitude', 'asc');"></i>
							<i class="icon-<?php echo "lib_address.latitude" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAddress', 'lib_address.latitude', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibAddress();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAddress_lib_address.name" type="text" class="span12 srch-libAddress"
						value="<?php echo isset($this->result['LibAddress']['Search']['lib_address.name']) ? $this->result['LibAddress']['Search']['lib_address.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAddress_lib_city.name" type="text" class="span12 srch-libAddress"
						value="<?php echo isset($this->result['LibAddress']['Search']['lib_city.name']) ? $this->result['LibAddress']['Search']['lib_city.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAddress_lib_address.address" type="text" class="span12 srch-libAddress"
						value="<?php echo isset($this->result['LibAddress']['Search']['lib_address.address']) ? $this->result['LibAddress']['Search']['lib_address.address'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAddress_lib_address.postal_code" type="text" class="span12 srch-libAddress"
						value="<?php echo isset($this->result['LibAddress']['Search']['lib_address.postal_code']) ? $this->result['LibAddress']['Search']['lib_address.postal_code'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAddress_lib_address.latitude" type="text" class="span12 srch-libAddress"
						value="<?php echo isset($this->result['LibAddress']['Search']['lib_address.latitude']) ? $this->result['LibAddress']['Search']['lib_address.latitude'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libAddress');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibAddress"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["lib_city_name"]; ?></td>
					<td><?php echo $record["address"]; ?></td>
					<td><?php echo $record["postal_code"]; ?></td>
					<td><?php echo $record["latitude"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibAddress(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibAddress"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libAddressData = <?php echo Zend_Json::encode($this->data["LibAddress"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libAddress"]();
		});
		$(".srch-libAddress").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libAddress"]();
		    }
		});
	});
	
</script>