<!-- LibAddress: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-wide modal-up hide fade" id="modalLibAddress">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libAddressModalHeading">Edit Lib Address</h3>
	  </div>
		<form id="libAddressForm" class="modal-form">
		  <div class="modal-body modal-high">
			  <div class="span6">
		  		<div class="control-group">
		    		<label for="libAddress_name"><b>Name *</b></label>
						<input id="libAddress_name" name="name" type="text"
							form-id="libAddress" class="span12 required" maxlength="50">
					</div>
		  		<div class="control-group">
				  	<label for="libAddress_lib_country_id"><b>Lib Country</b></label>
						<select id="libAddress_lib_country_id" name="lib_country_id"
							form-id="libAddress" class="span12 data-dependant-parent required" 
							data='{"dependant":"libAddress_lib_region_id","item":"Lib Region","title":"Lib Country","filterField":"lib_country_id"}'>
							<option value="">-- Select Lib Country --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listLibCountry"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
				  	<label for="libAddress_lib_region_id"><b>Lib Region</b></label>
						<select id="libAddress_lib_region_id" name="lib_region_id"
							form-id="libAddress" class="span12 data-dependant-chain required" 
							data='{"parent":"libAddress_lib_country_id","dependant":"libAddress_lib_city_id","item":"Lib City","title":"Lib Region","filterField":"lib_region_id"}'>
							<option value="">--- Select Lib Country ---</option>
							
						</select>
					</div>
		  		<div class="control-group">
				  	<label for="libAddress_lib_city_id"><b>Lib City</b></label>
						<select id="libAddress_lib_city_id" name="lib_city_id"
							form-id="libAddress" class="span12 data-dependant-child required" 
							data='{"parent":"libAddress_lib_region_id"}'>
							<option value="">--- Select Lib Region ---</option>
							
						</select>
					</div></div>
			  <div class="span6">
		  		<div class="control-group">
		    		<label for="libAddress_address"><b>Address</b></label>
						<input id="libAddress_address" name="address" type="text"
							form-id="libAddress" class="span12 " maxlength="250">
					</div>
		  		<div class="control-group">
		    		<label for="libAddress_postal_code"><b>Postal Code</b></label>
						<input id="libAddress_postal_code" name="postal_code" type="text"
							form-id="libAddress" class="span6 " maxlength="10">
					</div>
		  		<div class="control-group">
		    		<label for="libAddress_latitude"><b>Latitude</b></label>
						<input id="libAddress_latitude" name="latitude" type="text"
							form-id="libAddress" class="span4  digits" >
					</div>
		  		<div class="control-group">
		    		<label for="libAddress_longitude"><b>Longitude</b></label>
						<input id="libAddress_longitude" name="longitude" type="text"
							form-id="libAddress" class="span4  digits" >
					</div>
				<input type="hidden" id="libAddress_id" name="id" form-id="libAddress">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibAddress: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libAddressForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libAddress", "libAddress", "api/data/" + mode,
			  	"LibAddressGrid", theme + "/lib-address-grid",
					false, true, false, {});
		  }
		});
	});
</script>