<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ItemGrid",
		"item-grid",
		$this->result["Item"]["Paging"]["CurrentPage"],
		$this->result["Item"]["Paging"]["TotalPages"],
		$this->result["Item"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Item"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "item.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('item', 'item.name', 'asc');"></i>
							<i class="icon-<?php echo "item.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('item', 'item.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "item.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('item', 'item.created', 'asc');"></i>
							<i class="icon-<?php echo "item.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('item', 'item.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "item.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('item', 'item.updated', 'asc');"></i>
							<i class="icon-<?php echo "item.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('item', 'item.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addItem();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_item_item.name" type="text" class="span12 srch-item"
						value="<?php echo isset($this->result['Item']['Search']['item.name']) ? $this->result['Item']['Search']['item.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_item_item.created" type="text" class="span12 srch-item"
						value="<?php echo isset($this->result['Item']['Search']['item.created']) ? $this->result['Item']['Search']['item.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_item_item.updated" type="text" class="span12 srch-item"
						value="<?php echo isset($this->result['Item']['Search']['item.updated']) ? $this->result['Item']['Search']['item.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-item');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Item"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editItem(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Item"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var itemData = <?php echo Zend_Json::encode($this->data["Item"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-item"]();
		});
		$(".srch-item").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-item"]();
		    }
		});
	});

</script>