<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AssetDescriptionGrid",
		"asset-description-grid",
		$this->result["AssetDescription"]["Paging"]["CurrentPage"],
		$this->result["AssetDescription"]["Paging"]["TotalPages"],
		$this->result["AssetDescription"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["AssetDescription"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Asset Sub Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_description.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetDescription', 'asset_description.name', 'asc');"></i>
							<i class="icon-<?php echo "asset_description.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetDescription', 'asset_description.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_description.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetDescription', 'asset_description.name', 'asc');"></i>
							<i class="icon-<?php echo "asset_description.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetDescription', 'asset_description.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_description.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetDescription', 'asset_description.created', 'asc');"></i>
							<i class="icon-<?php echo "asset_description.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetDescription', 'asset_description.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_description.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetDescription', 'asset_description.updated', 'asc');"></i>
							<i class="icon-<?php echo "asset_description.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetDescription', 'asset_description.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAssetDescription();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetDescription_asset_sub_type.name" type="text" class="span12 srch-assetDescription"
						value="<?php echo isset($this->result['AssetDescription']['Search']['asset_sub_type.name']) ? $this->result['AssetDescription']['Search']['asset_sub_type.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetDescription_asset_description.name" type="text" class="span12 srch-assetDescription"
						value="<?php echo isset($this->result['AssetDescription']['Search']['asset_description.name']) ? $this->result['AssetDescription']['Search']['asset_description.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetDescription_asset_description.created" type="text" class="span12 srch-assetDescription"
						value="<?php echo isset($this->result['AssetDescription']['Search']['asset_description.created']) ? $this->result['AssetDescription']['Search']['asset_description.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetDescription_asset_description.updated" type="text" class="span12 srch-assetDescription"
						value="<?php echo isset($this->result['AssetDescription']['Search']['asset_description.updated']) ? $this->result['AssetDescription']['Search']['asset_description.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-assetDescription');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["AssetDescription"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["asset_sub_type_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAssetDescription(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["AssetDescription"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var assetDescriptionData = <?php echo Zend_Json::encode($this->data["AssetDescription"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-assetDescription"]();
		});
		$(".srch-assetDescription").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-assetDescription"]();
		    }
		});
	});
	
</script>