<!-- AssetDescription: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalAssetDescription">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="assetDescriptionModalHeading">Edit Asset Description</h3>
	  </div>
		<form id="assetDescriptionForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="assetDescription_asset_sub_type_id"><b>Asset Sub Type *</b></label>
						<select id="assetDescription_asset_sub_type_id" name="asset_sub_type_id"
							form-id="assetDescription" class="span12 required" >
							<option value="">-- Select Asset Sub Type * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listAssetSubType"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="assetDescription_name"><b>Name *</b></label>
						<input id="assetDescription_name" name="name" type="text"
							form-id="assetDescription" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="assetDescription_id" name="id" form-id="assetDescription">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] AssetDescription: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#assetDescriptionForm").validate({
		  submitHandler: function(form) {
			  doUpdate("assetDescription", "assetDescription", "api/data/" + mode,
			  	"AssetDescriptionGrid", theme + "/asset-description-grid",
					false, true, false, {});
		  }
		});
	});
</script>