<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibCountryGrid",
		"lib-country-grid",
		$this->result["LibCountry"]["Paging"]["CurrentPage"],
		$this->result["LibCountry"]["Paging"]["TotalPages"],
		$this->result["LibCountry"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibCountry"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_country.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCountry', 'lib_country.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_country.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCountry', 'lib_country.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Country Code Iso</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_country.country_code_iso" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCountry', 'lib_country.country_code_iso', 'asc');"></i>
							<i class="icon-<?php echo "lib_country.country_code_iso" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCountry', 'lib_country.country_code_iso', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Country Code Fips</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_country.country_code_fips" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCountry', 'lib_country.country_code_fips', 'asc');"></i>
							<i class="icon-<?php echo "lib_country.country_code_fips" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCountry', 'lib_country.country_code_fips', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Dialing Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_country.dialing_code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCountry', 'lib_country.dialing_code', 'asc');"></i>
							<i class="icon-<?php echo "lib_country.dialing_code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCountry', 'lib_country.dialing_code', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibCountry();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCountry_lib_country.name" type="text" class="span12 srch-libCountry"
						value="<?php echo isset($this->result['LibCountry']['Search']['lib_country.name']) ? $this->result['LibCountry']['Search']['lib_country.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCountry_lib_country.country_code_iso" type="text" class="span12 srch-libCountry"
						value="<?php echo isset($this->result['LibCountry']['Search']['lib_country.country_code_iso']) ? $this->result['LibCountry']['Search']['lib_country.country_code_iso'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCountry_lib_country.country_code_fips" type="text" class="span12 srch-libCountry"
						value="<?php echo isset($this->result['LibCountry']['Search']['lib_country.country_code_fips']) ? $this->result['LibCountry']['Search']['lib_country.country_code_fips'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCountry_lib_country.dialing_code" type="text" class="span12 srch-libCountry"
						value="<?php echo isset($this->result['LibCountry']['Search']['lib_country.dialing_code']) ? $this->result['LibCountry']['Search']['lib_country.dialing_code'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libCountry');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibCountry"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["country_code_iso"]; ?></td>
					<td><?php echo $record["country_code_fips"]; ?></td>
					<td><?php echo $record["dialing_code"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibCountry(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibCountry"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libCountryData = <?php echo Zend_Json::encode($this->data["LibCountry"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libCountry"]();
		});
		$(".srch-libCountry").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libCountry"]();
		    }
		});
	});
	
</script>