<!-- LibCountry: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibCountry">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libCountryModalHeading">Edit Lib Country</h3>
	  </div>
		<form id="libCountryForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libCountry_name"><b>Name *</b></label>
						<input id="libCountry_name" name="name" type="text"
							form-id="libCountry" class="span12 required" maxlength="50">
					</div>
		  		<div class="control-group">
		    		<label for="libCountry_country_code_iso"><b>Country Code Iso</b></label>
						<input id="libCountry_country_code_iso" name="country_code_iso" type="text"
							form-id="libCountry" class="span4 " maxlength="2">
					</div>
		  		<div class="control-group">
		    		<label for="libCountry_country_code_fips"><b>Country Code Fips</b></label>
						<input id="libCountry_country_code_fips" name="country_code_fips" type="text"
							form-id="libCountry" class="span4 " maxlength="2">
					</div>
		  		<div class="control-group">
		    		<label class="checkbox" for="libCountry_dialing_code">
			    		<input type="checkbox" id="libCountry_dialing_code" name="dialing_code"
			    			value="dialing_code" form-id="libCountry" checked>
			    		&nbsp;<b>Dialing Code</b>
		    		</label>
					</div>
				<input type="hidden" id="libCountry_id" name="id" form-id="libCountry">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibCountry: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libCountryForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libCountry", "libCountry", "api/data/" + mode,
			  	"LibCountryGrid", theme + "/lib-country-grid",
					false, true, false, {});
		  }
		});
	});
</script>