<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibActionReferenceGrid",
		"lib-action-reference-grid",
		$this->result["LibActionReference"]["Paging"]["CurrentPage"],
		$this->result["LibActionReference"]["Paging"]["TotalPages"],
		$this->result["LibActionReference"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibActionReference"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Hash Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_action_reference.hash_code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libActionReference', 'lib_action_reference.hash_code', 'asc');"></i>
							<i class="icon-<?php echo "lib_action_reference.hash_code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libActionReference', 'lib_action_reference.hash_code', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Component</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_action_reference.component" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libActionReference', 'lib_action_reference.component', 'asc');"></i>
							<i class="icon-<?php echo "lib_action_reference.component" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libActionReference', 'lib_action_reference.component', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Action</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_action_reference.action" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libActionReference', 'lib_action_reference.action', 'asc');"></i>
							<i class="icon-<?php echo "lib_action_reference.action" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libActionReference', 'lib_action_reference.action', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Params</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_action_reference.params" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libActionReference', 'lib_action_reference.params', 'asc');"></i>
							<i class="icon-<?php echo "lib_action_reference.params" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libActionReference', 'lib_action_reference.params', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_action_reference.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libActionReference', 'lib_action_reference.created', 'asc');"></i>
							<i class="icon-<?php echo "lib_action_reference.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libActionReference', 'lib_action_reference.created', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibActionReference();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libActionReference_lib_action_reference.hash_code" type="text" class="span12 srch-libActionReference"
						value="<?php echo isset($this->result['LibActionReference']['Search']['lib_action_reference.hash_code']) ? $this->result['LibActionReference']['Search']['lib_action_reference.hash_code'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libActionReference_lib_action_reference.component" type="text" class="span12 srch-libActionReference"
						value="<?php echo isset($this->result['LibActionReference']['Search']['lib_action_reference.component']) ? $this->result['LibActionReference']['Search']['lib_action_reference.component'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libActionReference_lib_action_reference.action" type="text" class="span12 srch-libActionReference"
						value="<?php echo isset($this->result['LibActionReference']['Search']['lib_action_reference.action']) ? $this->result['LibActionReference']['Search']['lib_action_reference.action'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libActionReference_lib_action_reference.params" type="text" class="span12 srch-libActionReference"
						value="<?php echo isset($this->result['LibActionReference']['Search']['lib_action_reference.params']) ? $this->result['LibActionReference']['Search']['lib_action_reference.params'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libActionReference_lib_action_reference.created" type="text" class="span12 srch-libActionReference"
						value="<?php echo isset($this->result['LibActionReference']['Search']['lib_action_reference.created']) ? $this->result['LibActionReference']['Search']['lib_action_reference.created'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libActionReference');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibActionReference"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["hash_code"]; ?></td>
					<td><?php echo $record["component"]; ?></td>
					<td><?php echo $record["action"]; ?></td>
					<td><?php echo $record["params"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibActionReference(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibActionReference"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libActionReferenceData = <?php echo Zend_Json::encode($this->data["LibActionReference"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libActionReference"]();
		});
		$(".srch-libActionReference").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libActionReference"]();
		    }
		});
	});
	
</script>