<!-- LibActionReference: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibActionReference">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libActionReferenceModalHeading">Edit Lib Action Reference</h3>
	  </div>
		<form id="libActionReferenceForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libActionReference_hash_code"><b>Hash Code *</b></label>
						<input id="libActionReference_hash_code" name="hash_code" type="text"
							form-id="libActionReference" class="span10 required" maxlength="40">
					</div>
		  		<div class="control-group">
		    		<label for="libActionReference_component"><b>Component *</b></label>
						<input id="libActionReference_component" name="component" type="text"
							form-id="libActionReference" class="span12 required" maxlength="250">
					</div>
		  		<div class="control-group">
		    		<label for="libActionReference_action"><b>Action *</b></label>
						<input id="libActionReference_action" name="action" type="text"
							form-id="libActionReference" class="span12 required" maxlength="250">
					</div>
		  		<div class="control-group">
		    		<label for="libActionReference_params"><b>Params</b></label>
						<input id="libActionReference_params" name="params" type="text"
							form-id="libActionReference" class="span12 " maxlength="250">
					</div>
		  		<div class="control-group">
			  		<label for="libActionReference_data_packet"><b>Data Packet</b></label>
						<textarea id="libActionReference_data_packet" name="data_packet" rows="5"
							form-id="libActionReference" class="span12 " maxlength="65535"></textarea>
					</div>
				<input type="hidden" id="libActionReference_id" name="id" form-id="libActionReference">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibActionReference: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libActionReferenceForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libActionReference", "libActionReference", "api/data/" + mode,
			  	"LibActionReferenceGrid", theme + "/lib-action-reference-grid",
					false, true, false, {});
		  }
		});
	});
</script>