<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibContactGrid",
		"lib-contact-grid",
		$this->result["LibContact"]["Paging"]["CurrentPage"],
		$this->result["LibContact"]["Paging"]["TotalPages"],
		$this->result["LibContact"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibContact"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>First Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_contact.first_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libContact', 'lib_contact.first_name', 'asc');"></i>
							<i class="icon-<?php echo "lib_contact.first_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libContact', 'lib_contact.first_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Family Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_contact.family_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libContact', 'lib_contact.family_name', 'asc');"></i>
							<i class="icon-<?php echo "lib_contact.family_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libContact', 'lib_contact.family_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mobile</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_contact.mobile" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libContact', 'lib_contact.mobile', 'asc');"></i>
							<i class="icon-<?php echo "lib_contact.mobile" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libContact', 'lib_contact.mobile', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Office</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_contact.office" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libContact', 'lib_contact.office', 'asc');"></i>
							<i class="icon-<?php echo "lib_contact.office" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libContact', 'lib_contact.office', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Fax</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_contact.fax" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libContact', 'lib_contact.fax', 'asc');"></i>
							<i class="icon-<?php echo "lib_contact.fax" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libContact', 'lib_contact.fax', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibContact();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libContact_lib_contact.first_name" type="text" class="span12 srch-libContact"
						value="<?php echo isset($this->result['LibContact']['Search']['lib_contact.first_name']) ? $this->result['LibContact']['Search']['lib_contact.first_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libContact_lib_contact.family_name" type="text" class="span12 srch-libContact"
						value="<?php echo isset($this->result['LibContact']['Search']['lib_contact.family_name']) ? $this->result['LibContact']['Search']['lib_contact.family_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libContact_lib_contact.mobile" type="text" class="span12 srch-libContact"
						value="<?php echo isset($this->result['LibContact']['Search']['lib_contact.mobile']) ? $this->result['LibContact']['Search']['lib_contact.mobile'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libContact_lib_contact.office" type="text" class="span12 srch-libContact"
						value="<?php echo isset($this->result['LibContact']['Search']['lib_contact.office']) ? $this->result['LibContact']['Search']['lib_contact.office'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libContact_lib_contact.fax" type="text" class="span12 srch-libContact"
						value="<?php echo isset($this->result['LibContact']['Search']['lib_contact.fax']) ? $this->result['LibContact']['Search']['lib_contact.fax'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libContact');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibContact"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["first_name"]; ?></td>
					<td><?php echo $record["family_name"]; ?></td>
					<td><?php echo $record["mobile"]; ?></td>
					<td><?php echo $record["office"]; ?></td>
					<td><?php echo $record["fax"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibContact(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibContact"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libContactData = <?php echo Zend_Json::encode($this->data["LibContact"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libContact"]();
		});
		$(".srch-libContact").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libContact"]();
		    }
		});
	});
	
</script>