<!-- AssetSubDescription: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalAssetSubDescription">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="assetSubDescriptionModalHeading">Edit Asset Sub Description</h3>
	  </div>
		<form id="assetSubDescriptionForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="assetSubDescription_asset_description_id"><b>Asset Description *</b></label>
						<select id="assetSubDescription_asset_description_id" name="asset_description_id"
							form-id="assetSubDescription" class="span12 required" >
							<option value="">-- Select Asset Description * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listAssetDescription"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="assetSubDescription_name"><b>Name *</b></label>
						<input id="assetSubDescription_name" name="name" type="text"
							form-id="assetSubDescription" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="assetSubDescription_id" name="id" form-id="assetSubDescription">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] AssetSubDescription: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#assetSubDescriptionForm").validate({
		  submitHandler: function(form) {
			  doUpdate("assetSubDescription", "assetSubDescription", "api/data/" + mode,
			  	"AssetSubDescriptionGrid", theme + "/asset-sub-description-grid",
					false, true, false, {});
		  }
		});
	});
</script>