<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AssetSubDescriptionGrid",
		"asset-sub-description-grid",
		$this->result["AssetSubDescription"]["Paging"]["CurrentPage"],
		$this->result["AssetSubDescription"]["Paging"]["TotalPages"],
		$this->result["AssetSubDescription"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["AssetSubDescription"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Asset Description</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_description.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubDescription', 'asset_sub_description.name', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_description.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubDescription', 'asset_sub_description.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_description.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubDescription', 'asset_sub_description.name', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_description.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubDescription', 'asset_sub_description.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_description.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubDescription', 'asset_sub_description.created', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_description.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubDescription', 'asset_sub_description.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset_sub_description.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('assetSubDescription', 'asset_sub_description.updated', 'asc');"></i>
							<i class="icon-<?php echo "asset_sub_description.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('assetSubDescription', 'asset_sub_description.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAssetSubDescription();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubDescription_asset_description.name" type="text" class="span12 srch-assetSubDescription"
						value="<?php echo isset($this->result['AssetSubDescription']['Search']['asset_description.name']) ? $this->result['AssetSubDescription']['Search']['asset_description.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubDescription_asset_sub_description.name" type="text" class="span12 srch-assetSubDescription"
						value="<?php echo isset($this->result['AssetSubDescription']['Search']['asset_sub_description.name']) ? $this->result['AssetSubDescription']['Search']['asset_sub_description.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubDescription_asset_sub_description.created" type="text" class="span12 srch-assetSubDescription"
						value="<?php echo isset($this->result['AssetSubDescription']['Search']['asset_sub_description.created']) ? $this->result['AssetSubDescription']['Search']['asset_sub_description.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_assetSubDescription_asset_sub_description.updated" type="text" class="span12 srch-assetSubDescription"
						value="<?php echo isset($this->result['AssetSubDescription']['Search']['asset_sub_description.updated']) ? $this->result['AssetSubDescription']['Search']['asset_sub_description.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-assetSubDescription');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["AssetSubDescription"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["asset_description_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAssetSubDescription(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["AssetSubDescription"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var assetSubDescriptionData = <?php echo Zend_Json::encode($this->data["AssetSubDescription"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-assetSubDescription"]();
		});
		$(".srch-assetSubDescription").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-assetSubDescription"]();
		    }
		});
	});
	
</script>