
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- AssetSubDescription: Data Grid -->
<span id="AssetSubDescriptionGrid">
<?php include_once("asset-sub-description-grid.phtml");?>
</span>
<!-- [End] AssetSubDescription: Data Grid -->

<!-- AssetSubDescription: Modal Form -->
<?php include_once("asset-sub-description-modal.phtml");?>
<!-- [End] AssetSubDescription: Modal Form -->


<script type="text/javascript">

	var theme = "source/asset-sub-description";

	$(document).ready(function() {
		$("#navAssetSubDescription").addClass("active");
		searchHandler["srch-assetSubDescription"] = {
				action: theme + "/asset-sub-description-grid",
				container: "AssetSubDescriptionGrid"
		};
    searchStack["srch-assetSubDescription"] = wrapFunction(search, this, ["srch-assetSubDescription"]);
	});

	function addAssetSubDescription(id) {
		//$("#assetSubDescriptionModalHeading").html("Add New Asset Sub Description");
		mode = "create";
		clearForm("assetSubDescription", "modalAssetSubDescription");
	}

	function editAssetSubDescription(id) {
		//$("#assetSubDescriptionModalHeading").html("Edit Asset Sub Description");
		mode = "update";
		populateForm("assetSubDescription", "asset_sub_description", assetSubDescriptionData[id], "modalAssetSubDescription");
	}

</script>