<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ConfigGrid",
		"config-grid",
		$this->result["Config"]["Paging"]["CurrentPage"],
		$this->result["Config"]["Paging"]["TotalPages"],
		$this->result["Config"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Config"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Date Format</b>
						<div class="pull-right">
							<i class="icon-<?php echo "config.date_format" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('config', 'config.date_format', 'asc');"></i>
							<i class="icon-<?php echo "config.date_format" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('config', 'config.date_format', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Time Format</b>
						<div class="pull-right">
							<i class="icon-<?php echo "config.time_format" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('config', 'config.time_format', 'asc');"></i>
							<i class="icon-<?php echo "config.time_format" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('config', 'config.time_format', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Currency Prefix</b>
						<div class="pull-right">
							<i class="icon-<?php echo "config.currency_prefix" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('config', 'config.currency_prefix', 'asc');"></i>
							<i class="icon-<?php echo "config.currency_prefix" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('config', 'config.currency_prefix', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Vat Percentage</b>
						<div class="pull-right">
							<i class="icon-<?php echo "config.vat_percentage" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('config', 'config.vat_percentage', 'asc');"></i>
							<i class="icon-<?php echo "config.vat_percentage" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('config', 'config.vat_percentage', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Notification Source Email</b>
						<div class="pull-right">
							<i class="icon-<?php echo "config.notification_source_email" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('config', 'config.notification_source_email', 'asc');"></i>
							<i class="icon-<?php echo "config.notification_source_email" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('config', 'config.notification_source_email', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addConfig();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_config_config.date_format" type="text" class="span12 srch-config"
						value="<?php echo isset($this->result['Config']['Search']['config.date_format']) ? $this->result['Config']['Search']['config.date_format'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_config_config.time_format" type="text" class="span12 srch-config"
						value="<?php echo isset($this->result['Config']['Search']['config.time_format']) ? $this->result['Config']['Search']['config.time_format'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_config_config.currency_prefix" type="text" class="span12 srch-config"
						value="<?php echo isset($this->result['Config']['Search']['config.currency_prefix']) ? $this->result['Config']['Search']['config.currency_prefix'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_config_config.vat_percentage" type="text" class="span12 srch-config"
						value="<?php echo isset($this->result['Config']['Search']['config.vat_percentage']) ? $this->result['Config']['Search']['config.vat_percentage'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_config_config.notification_source_email" type="text" class="span12 srch-config"
						value="<?php echo isset($this->result['Config']['Search']['config.notification_source_email']) ? $this->result['Config']['Search']['config.notification_source_email'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-config');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Config"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["date_format"]; ?></td>
					<td><?php echo $record["time_format"]; ?></td>
					<td><?php echo $record["currency_prefix"]; ?></td>
					<td><?php echo $record["vat_percentage"]; ?></td>
					<td><?php echo $record["notification_source_email"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editConfig(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Config"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var configData = <?php echo Zend_Json::encode($this->data["Config"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-config"]();
		});
		$(".srch-config").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-config"]();
		    }
		});
	});

</script>