<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"BuildingGrid",
		"building-grid",
		$this->result["Building"]["Paging"]["CurrentPage"],
		$this->result["Building"]["Paging"]["TotalPages"],
		$this->result["Building"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Building"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Location</b>
						<div class="pull-right">
							<i class="icon-<?php echo "building.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('building', 'building.name', 'asc');"></i>
							<i class="icon-<?php echo "building.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('building', 'building.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "building.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('building', 'building.name', 'asc');"></i>
							<i class="icon-<?php echo "building.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('building', 'building.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "building.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('building', 'building.created', 'asc');"></i>
							<i class="icon-<?php echo "building.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('building', 'building.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "building.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('building', 'building.updated', 'asc');"></i>
							<i class="icon-<?php echo "building.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('building', 'building.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addBuilding();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_building_location.name" type="text" class="span12 srch-building"
						value="<?php echo isset($this->result['Building']['Search']['location.name']) ? $this->result['Building']['Search']['location.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_building_building.name" type="text" class="span12 srch-building"
						value="<?php echo isset($this->result['Building']['Search']['building.name']) ? $this->result['Building']['Search']['building.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_building_building.created" type="text" class="span12 srch-building"
						value="<?php echo isset($this->result['Building']['Search']['building.created']) ? $this->result['Building']['Search']['building.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_building_building.updated" type="text" class="span12 srch-building"
						value="<?php echo isset($this->result['Building']['Search']['building.updated']) ? $this->result['Building']['Search']['building.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-building');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Building"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["location_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editBuilding(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Building"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var buildingData = <?php echo Zend_Json::encode($this->data["Building"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-building"]();
		});
		$(".srch-building").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-building"]();
		    }
		});
	});
	
</script>