<!-- Building: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalBuilding">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="buildingModalHeading">Edit Building</h3>
	  </div>
		<form id="buildingForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="building_location_id"><b>Location *</b></label>
						<select id="building_location_id" name="location_id"
							form-id="building" class="span12 required" >
							<option value="">-- Select Location * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listLocation"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="building_name"><b>Name *</b></label>
						<input id="building_name" name="name" type="text"
							form-id="building" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="building_id" name="id" form-id="building">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] Building: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#buildingForm").validate({
		  submitHandler: function(form) {
			  doUpdate("building", "building", "api/data/" + mode,
			  	"BuildingGrid", theme + "/building-grid",
					false, true, false, {});
		  }
		});
	});
</script>