
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- Building: Data Grid -->
<span id="BuildingGrid">
<?php include_once("building-grid.phtml");?>
</span>
<!-- [End] Building: Data Grid -->

<!-- Building: Modal Form -->
<?php include_once("building-modal.phtml");?>
<!-- [End] Building: Modal Form -->


<script type="text/javascript">

	var theme = "source/building";

	$(document).ready(function() {
		$("#navBuilding").addClass("active");
		searchHandler["srch-building"] = {
				action: theme + "/building-grid",
				container: "BuildingGrid"
		};
    searchStack["srch-building"] = wrapFunction(search, this, ["srch-building"]);
	});

	function addBuilding(id) {
		//$("#buildingModalHeading").html("Add New Building");
		mode = "create";
		clearForm("building", "modalBuilding");
	}

	function editBuilding(id) {
		//$("#buildingModalHeading").html("Edit Building");
		mode = "update";
		populateForm("building", "building", buildingData[id], "modalBuilding");
	}

</script>