<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ContentGrid",
		"content-grid",
		$this->result["Content"]["Paging"]["CurrentPage"],
		$this->result["Content"]["Paging"]["TotalPages"],
		$this->result["Content"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Content"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "content.type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('content', 'content.type', 'asc');"></i>
							<i class="icon-<?php echo "content.type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('content', 'content.type', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "content.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('content', 'content.name', 'asc');"></i>
							<i class="icon-<?php echo "content.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('content', 'content.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "content.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('content', 'content.created', 'asc');"></i>
							<i class="icon-<?php echo "content.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('content', 'content.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "content.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('content', 'content.updated', 'asc');"></i>
							<i class="icon-<?php echo "content.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('content', 'content.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addContent();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_content_content.type" type="text" class="span12 srch-content"
						value="<?php echo isset($this->result['Content']['Search']['content.type']) ? $this->result['Content']['Search']['content.type'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_content_content.name" type="text" class="span12 srch-content"
						value="<?php echo isset($this->result['Content']['Search']['content.name']) ? $this->result['Content']['Search']['content.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_content_content.created" type="text" class="span12 srch-content"
						value="<?php echo isset($this->result['Content']['Search']['content.created']) ? $this->result['Content']['Search']['content.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_content_content.updated" type="text" class="span12 srch-content"
						value="<?php echo isset($this->result['Content']['Search']['content.updated']) ? $this->result['Content']['Search']['content.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-content');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Content"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["type"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editContent(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Content"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var contentData = <?php echo Zend_Json::encode($this->data["Content"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-content"]();
		});
		$(".srch-content").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-content"]();
		    }
		});
	});
	
</script>