
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- Content: Data Grid -->
<span id="ContentGrid">
<?php include_once("content-grid.phtml");?>
</span>
<!-- [End] Content: Data Grid -->

<!-- Content: Modal Form -->
<?php include_once("content-modal.phtml");?>
<!-- [End] Content: Modal Form -->


<script type="text/javascript">

	var theme = "source/content";

	$(document).ready(function() {
		$("#navContent").addClass("active");
		searchHandler["srch-content"] = {
				action: theme + "/content-grid",
				container: "ContentGrid"
		};
    searchStack["srch-content"] = wrapFunction(search, this, ["srch-content"]);
	});

	function addContent(id) {
		//$("#contentModalHeading").html("Add New Content");
		mode = "create";
		clearForm("content", "modalContent");
	}

	function editContent(id) {
		//$("#contentModalHeading").html("Edit Content");
		mode = "update";
		populateForm("content", "content", contentData[id], "modalContent");
	}

</script>