<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ContactRequestGrid",
		"contact-request-grid",
		$this->result["ContactRequest"]["Paging"]["CurrentPage"],
		$this->result["ContactRequest"]["Paging"]["TotalPages"],
		$this->result["ContactRequest"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["ContactRequest"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Person Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "contact_request.person_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('contactRequest', 'contact_request.person_name', 'asc');"></i>
							<i class="icon-<?php echo "contact_request.person_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('contactRequest', 'contact_request.person_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Trading Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "contact_request.trading_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('contactRequest', 'contact_request.trading_name', 'asc');"></i>
							<i class="icon-<?php echo "contact_request.trading_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('contactRequest', 'contact_request.trading_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Email</b>
						<div class="pull-right">
							<i class="icon-<?php echo "contact_request.email" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('contactRequest', 'contact_request.email', 'asc');"></i>
							<i class="icon-<?php echo "contact_request.email" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('contactRequest', 'contact_request.email', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mobile</b>
						<div class="pull-right">
							<i class="icon-<?php echo "contact_request.mobile" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('contactRequest', 'contact_request.mobile', 'asc');"></i>
							<i class="icon-<?php echo "contact_request.mobile" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('contactRequest', 'contact_request.mobile', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Telephone</b>
						<div class="pull-right">
							<i class="icon-<?php echo "contact_request.telephone" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('contactRequest', 'contact_request.telephone', 'asc');"></i>
							<i class="icon-<?php echo "contact_request.telephone" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('contactRequest', 'contact_request.telephone', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addContactRequest();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_contactRequest_contact_request.person_name" type="text" class="span12 srch-contactRequest"
						value="<?php echo isset($this->result['ContactRequest']['Search']['contact_request.person_name']) ? $this->result['ContactRequest']['Search']['contact_request.person_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_contactRequest_contact_request.trading_name" type="text" class="span12 srch-contactRequest"
						value="<?php echo isset($this->result['ContactRequest']['Search']['contact_request.trading_name']) ? $this->result['ContactRequest']['Search']['contact_request.trading_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_contactRequest_contact_request.email" type="text" class="span12 srch-contactRequest"
						value="<?php echo isset($this->result['ContactRequest']['Search']['contact_request.email']) ? $this->result['ContactRequest']['Search']['contact_request.email'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_contactRequest_contact_request.mobile" type="text" class="span12 srch-contactRequest"
						value="<?php echo isset($this->result['ContactRequest']['Search']['contact_request.mobile']) ? $this->result['ContactRequest']['Search']['contact_request.mobile'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_contactRequest_contact_request.telephone" type="text" class="span12 srch-contactRequest"
						value="<?php echo isset($this->result['ContactRequest']['Search']['contact_request.telephone']) ? $this->result['ContactRequest']['Search']['contact_request.telephone'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-contactRequest');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["ContactRequest"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["person_name"]; ?></td>
					<td><?php echo $record["trading_name"]; ?></td>
					<td><?php echo $record["email"]; ?></td>
					<td><?php echo $record["mobile"]; ?></td>
					<td><?php echo $record["telephone"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editContactRequest(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["ContactRequest"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var contactRequestData = <?php echo Zend_Json::encode($this->data["ContactRequest"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-contactRequest"]();
		});
		$(".srch-contactRequest").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-contactRequest"]();
		    }
		});
	});

</script>