
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- ContactRequest: Data Grid -->
<span id="ContactRequestGrid">
<?php include_once("contact-request-grid.phtml");?>
</span>
<!-- [End] ContactRequest: Data Grid -->

<!-- ContactRequest: Modal Form -->
<?php include_once("contact-request-modal.phtml");?>
<!-- [End] ContactRequest: Modal Form -->


<script type="text/javascript">

	var theme = "source/contact-request";

	$(document).ready(function() {
		$("#navContactRequest").addClass("active");
		searchHandler["srch-contactRequest"] = {
				action: theme + "/contact-request-grid",
				container: "ContactRequestGrid"
		};
    searchStack["srch-contactRequest"] = wrapFunction(search, this, ["srch-contactRequest"]);
	});

	function addContactRequest(id) {
		//$("#contactRequestModalHeading").html("Add New Contact Request");
		mode = "create";
		clearForm("contactRequest", "modalContactRequest");
	}

	function editContactRequest(id) {
		//$("#contactRequestModalHeading").html("Edit Contact Request");
		mode = "update";
		populateForm("contactRequest", "contact_request", contactRequestData[id], "modalContactRequest");
	}

</script>