<!-- LibPhoto: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibPhoto">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libPhotoModalHeading">Edit Lib Photo</h3>
	  </div>
		<form id="libPhotoForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libPhoto_mime_type"><b>Mime Type</b></label>
						<input id="libPhoto_mime_type" name="mime_type" type="text"
							form-id="libPhoto" class="span12 " maxlength="200">
					</div>
				<input type="hidden" id="libPhoto_id" name="id" form-id="libPhoto">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibPhoto: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libPhotoForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libPhoto", "libPhoto", "api/data/" + mode,
			  	"LibPhotoGrid", theme + "/lib-photo-grid",
					false, true, false, {});
		  }
		});
	});
</script>