<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibPhotoGrid",
		"lib-photo-grid",
		$this->result["LibPhoto"]["Paging"]["CurrentPage"],
		$this->result["LibPhoto"]["Paging"]["TotalPages"],
		$this->result["LibPhoto"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibPhoto"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Photo</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_photo.photo" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPhoto', 'lib_photo.photo', 'asc');"></i>
							<i class="icon-<?php echo "lib_photo.photo" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPhoto', 'lib_photo.photo', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Thumbnail</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_photo.thumbnail" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPhoto', 'lib_photo.thumbnail', 'asc');"></i>
							<i class="icon-<?php echo "lib_photo.thumbnail" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPhoto', 'lib_photo.thumbnail', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mime Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_photo.mime_type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPhoto', 'lib_photo.mime_type', 'asc');"></i>
							<i class="icon-<?php echo "lib_photo.mime_type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPhoto', 'lib_photo.mime_type', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibPhoto();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPhoto_lib_photo.photo" type="text" class="span12 srch-libPhoto"
						value="<?php echo isset($this->result['LibPhoto']['Search']['lib_photo.photo']) ? $this->result['LibPhoto']['Search']['lib_photo.photo'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPhoto_lib_photo.thumbnail" type="text" class="span12 srch-libPhoto"
						value="<?php echo isset($this->result['LibPhoto']['Search']['lib_photo.thumbnail']) ? $this->result['LibPhoto']['Search']['lib_photo.thumbnail'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPhoto_lib_photo.mime_type" type="text" class="span12 srch-libPhoto"
						value="<?php echo isset($this->result['LibPhoto']['Search']['lib_photo.mime_type']) ? $this->result['LibPhoto']['Search']['lib_photo.mime_type'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libPhoto');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibPhoto"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["photo"]; ?></td>
					<td><?php echo $record["thumbnail"]; ?></td>
					<td><?php echo $record["mime_type"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibPhoto(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibPhoto"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libPhotoData = <?php echo Zend_Json::encode($this->data["LibPhoto"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libPhoto"]();
		});
		$(".srch-libPhoto").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libPhoto"]();
		    }
		});
	});
	
</script>