<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ProfileGrid",
		"profile-grid",
		$this->result["Profile"]["Paging"]["CurrentPage"],
		$this->result["Profile"]["Paging"]["TotalPages"],
		$this->result["Profile"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Profile"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>First Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "profile.first_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('profile', 'profile.first_name', 'asc');"></i>
							<i class="icon-<?php echo "profile.first_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('profile', 'profile.first_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Family Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "profile.family_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('profile', 'profile.family_name', 'asc');"></i>
							<i class="icon-<?php echo "profile.family_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('profile', 'profile.family_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Id Number</b>
						<div class="pull-right">
							<i class="icon-<?php echo "profile.id_number" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('profile', 'profile.id_number', 'asc');"></i>
							<i class="icon-<?php echo "profile.id_number" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('profile', 'profile.id_number', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Date Of Birth</b>
						<div class="pull-right">
							<i class="icon-<?php echo "profile.date_of_birth" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('profile', 'profile.date_of_birth', 'asc');"></i>
							<i class="icon-<?php echo "profile.date_of_birth" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('profile', 'profile.date_of_birth', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mobile</b>
						<div class="pull-right">
							<i class="icon-<?php echo "profile.mobile" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('profile', 'profile.mobile', 'asc');"></i>
							<i class="icon-<?php echo "profile.mobile" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('profile', 'profile.mobile', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addProfile();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_profile_profile.first_name" type="text" class="span12 srch-profile"
						value="<?php echo isset($this->result['Profile']['Search']['profile.first_name']) ? $this->result['Profile']['Search']['profile.first_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_profile_profile.family_name" type="text" class="span12 srch-profile"
						value="<?php echo isset($this->result['Profile']['Search']['profile.family_name']) ? $this->result['Profile']['Search']['profile.family_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_profile_profile.id_number" type="text" class="span12 srch-profile"
						value="<?php echo isset($this->result['Profile']['Search']['profile.id_number']) ? $this->result['Profile']['Search']['profile.id_number'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_profile_profile.date_of_birth" type="text" class="span12 srch-profile"
						value="<?php echo isset($this->result['Profile']['Search']['profile.date_of_birth']) ? $this->result['Profile']['Search']['profile.date_of_birth'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_profile_profile.mobile" type="text" class="span12 srch-profile"
						value="<?php echo isset($this->result['Profile']['Search']['profile.mobile']) ? $this->result['Profile']['Search']['profile.mobile'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-profile');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Profile"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["first_name"]; ?></td>
					<td><?php echo $record["family_name"]; ?></td>
					<td><?php echo $record["id_number"]; ?></td>
					<td><?php echo $record["date_of_birth"]; ?></td>
					<td><?php echo $record["mobile"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editProfile(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Profile"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var profileData = <?php echo Zend_Json::encode($this->data["Profile"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-profile"]();
		});
		$(".srch-profile").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-profile"]();
		    }
		});
	});

</script>