
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- Room: Data Grid -->
<span id="RoomGrid">
<?php include_once("room-grid.phtml");?>
</span>
<!-- [End] Room: Data Grid -->

<!-- Room: Modal Form -->
<?php include_once("room-modal.phtml");?>
<!-- [End] Room: Modal Form -->


<script type="text/javascript">

	var theme = "source/room";

	$(document).ready(function() {
		$("#navRoom").addClass("active");
		searchHandler["srch-room"] = {
				action: theme + "/room-grid",
				container: "RoomGrid"
		};
    searchStack["srch-room"] = wrapFunction(search, this, ["srch-room"]);
	});

	function addRoom(id) {
		//$("#roomModalHeading").html("Add New Room");
		mode = "create";
		clearForm("room", "modalRoom");
	}

	function editRoom(id) {
		//$("#roomModalHeading").html("Edit Room");
		mode = "update";
		populateForm("room", "room", roomData[id], "modalRoom");
	}

</script>