<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"RoomGrid",
		"room-grid",
		$this->result["Room"]["Paging"]["CurrentPage"],
		$this->result["Room"]["Paging"]["TotalPages"],
		$this->result["Room"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Room"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Floor</b>
						<div class="pull-right">
							<i class="icon-<?php echo "room.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('room', 'room.name', 'asc');"></i>
							<i class="icon-<?php echo "room.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('room', 'room.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "room.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('room', 'room.name', 'asc');"></i>
							<i class="icon-<?php echo "room.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('room', 'room.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "room.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('room', 'room.created', 'asc');"></i>
							<i class="icon-<?php echo "room.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('room', 'room.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "room.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('room', 'room.updated', 'asc');"></i>
							<i class="icon-<?php echo "room.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('room', 'room.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addRoom();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_room_floor.name" type="text" class="span12 srch-room"
						value="<?php echo isset($this->result['Room']['Search']['floor.name']) ? $this->result['Room']['Search']['floor.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_room_room.name" type="text" class="span12 srch-room"
						value="<?php echo isset($this->result['Room']['Search']['room.name']) ? $this->result['Room']['Search']['room.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_room_room.created" type="text" class="span12 srch-room"
						value="<?php echo isset($this->result['Room']['Search']['room.created']) ? $this->result['Room']['Search']['room.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_room_room.updated" type="text" class="span12 srch-room"
						value="<?php echo isset($this->result['Room']['Search']['room.updated']) ? $this->result['Room']['Search']['room.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-room');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Room"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["floor_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editRoom(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Room"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var roomData = <?php echo Zend_Json::encode($this->data["Room"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-room"]();
		});
		$(".srch-room").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-room"]();
		    }
		});
	});
	
</script>