<!-- Room: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalRoom">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="roomModalHeading">Edit Room</h3>
	  </div>
		<form id="roomForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="room_floor_id"><b>Floor *</b></label>
						<select id="room_floor_id" name="floor_id"
							form-id="room" class="span12 required" >
							<option value="">-- Select Floor * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listFloor"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="room_name"><b>Name *</b></label>
						<input id="room_name" name="name" type="text"
							form-id="room" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="room_id" name="id" form-id="room">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] Room: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#roomForm").validate({
		  submitHandler: function(form) {
			  doUpdate("room", "room", "api/data/" + mode,
			  	"RoomGrid", theme + "/room-grid",
					false, true, false, {});
		  }
		});
	});
</script>