<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibPersonGrid",
		"lib-person-grid",
		$this->result["LibPerson"]["Paging"]["CurrentPage"],
		$this->result["LibPerson"]["Paging"]["TotalPages"],
		$this->result["LibPerson"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibPerson"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>First Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_person.first_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPerson', 'lib_person.first_name', 'asc');"></i>
							<i class="icon-<?php echo "lib_person.first_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPerson', 'lib_person.first_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Family Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_person.family_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPerson', 'lib_person.family_name', 'asc');"></i>
							<i class="icon-<?php echo "lib_person.family_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPerson', 'lib_person.family_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Id Number</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_person.id_number" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPerson', 'lib_person.id_number', 'asc');"></i>
							<i class="icon-<?php echo "lib_person.id_number" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPerson', 'lib_person.id_number', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_person.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPerson', 'lib_person.created', 'asc');"></i>
							<i class="icon-<?php echo "lib_person.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPerson', 'lib_person.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_person.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libPerson', 'lib_person.updated', 'asc');"></i>
							<i class="icon-<?php echo "lib_person.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libPerson', 'lib_person.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibPerson();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPerson_lib_person.first_name" type="text" class="span12 srch-libPerson"
						value="<?php echo isset($this->result['LibPerson']['Search']['lib_person.first_name']) ? $this->result['LibPerson']['Search']['lib_person.first_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPerson_lib_person.family_name" type="text" class="span12 srch-libPerson"
						value="<?php echo isset($this->result['LibPerson']['Search']['lib_person.family_name']) ? $this->result['LibPerson']['Search']['lib_person.family_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPerson_lib_person.id_number" type="text" class="span12 srch-libPerson"
						value="<?php echo isset($this->result['LibPerson']['Search']['lib_person.id_number']) ? $this->result['LibPerson']['Search']['lib_person.id_number'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPerson_lib_person.created" type="text" class="span12 srch-libPerson"
						value="<?php echo isset($this->result['LibPerson']['Search']['lib_person.created']) ? $this->result['LibPerson']['Search']['lib_person.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libPerson_lib_person.updated" type="text" class="span12 srch-libPerson"
						value="<?php echo isset($this->result['LibPerson']['Search']['lib_person.updated']) ? $this->result['LibPerson']['Search']['lib_person.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libPerson');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibPerson"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["first_name"]; ?></td>
					<td><?php echo $record["family_name"]; ?></td>
					<td><?php echo $record["id_number"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibPerson(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibPerson"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libPersonData = <?php echo Zend_Json::encode($this->data["LibPerson"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libPerson"]();
		});
		$(".srch-libPerson").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libPerson"]();
		    }
		});
	});
	
</script>