<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibNewsletterTemplateGrid",
		"lib-newsletter-template-grid",
		$this->result["LibNewsletterTemplate"]["Paging"]["CurrentPage"],
		$this->result["LibNewsletterTemplate"]["Paging"]["TotalPages"],
		$this->result["LibNewsletterTemplate"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibNewsletterTemplate"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter_template.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletterTemplate', 'lib_newsletter_template.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter_template.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletterTemplate', 'lib_newsletter_template.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Footer Lib Photo</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter_template.mime_type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletterTemplate', 'lib_newsletter_template.mime_type', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter_template.mime_type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletterTemplate', 'lib_newsletter_template.mime_type', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibNewsletterTemplate();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletterTemplate_lib_newsletter_template.name" type="text" class="span12 srch-libNewsletterTemplate"
						value="<?php echo isset($this->result['LibNewsletterTemplate']['Search']['lib_newsletter_template.name']) ? $this->result['LibNewsletterTemplate']['Search']['lib_newsletter_template.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletterTemplate_lib_photo.mime_type" type="text" class="span12 srch-libNewsletterTemplate"
						value="<?php echo isset($this->result['LibNewsletterTemplate']['Search']['lib_photo.mime_type']) ? $this->result['LibNewsletterTemplate']['Search']['lib_photo.mime_type'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libNewsletterTemplate');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibNewsletterTemplate"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["lib_photo_mime_type"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibNewsletterTemplate(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibNewsletterTemplate"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="2">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libNewsletterTemplateData = <?php echo Zend_Json::encode($this->data["LibNewsletterTemplate"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libNewsletterTemplate"]();
		});
		$(".srch-libNewsletterTemplate").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libNewsletterTemplate"]();
		    }
		});
	});
	
</script>