<!-- LibNewsletterTemplate: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibNewsletterTemplate">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libNewsletterTemplateModalHeading">Edit Lib Newsletter Template</h3>
	  </div>
		<form id="libNewsletterTemplateForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libNewsletterTemplate_name"><b>Name *</b></label>
						<input id="libNewsletterTemplate_name" name="name" type="text"
							form-id="libNewsletterTemplate" class="span12 required" maxlength="50">
					</div>
		  		<div class="control-group">
				  	<label for="libNewsletterTemplate_header_lib_photo_id"><b>Header Lib Photo *</b></label>
						<select id="libNewsletterTemplate_header_lib_photo_id" name="header_lib_photo_id"
							form-id="libNewsletterTemplate" class="span12 required" >
							<option value="">-- Select Header Lib Photo * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listHeaderLibPhoto"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
				  	<label for="libNewsletterTemplate_footer_lib_photo_id"><b>Footer Lib Photo *</b></label>
						<select id="libNewsletterTemplate_footer_lib_photo_id" name="footer_lib_photo_id"
							form-id="libNewsletterTemplate" class="span12 required" >
							<option value="">-- Select Footer Lib Photo * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listFooterLibPhoto"], false); ?>

						</select>
					</div>
				<input type="hidden" id="libNewsletterTemplate_id" name="id" form-id="libNewsletterTemplate">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibNewsletterTemplate: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libNewsletterTemplateForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libNewsletterTemplate", "libNewsletterTemplate", "api/data/" + mode,
			  	"LibNewsletterTemplateGrid", theme + "/lib-newsletter-template-grid",
					false, true, false, {});
		  }
		});
	});
</script>