
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- LibAttachment: Data Grid -->
<span id="LibAttachmentGrid">
<?php include_once("lib-attachment-grid.phtml");?>
</span>
<!-- [End] LibAttachment: Data Grid -->

<!-- LibAttachment: Modal Form -->
<?php include_once("lib-attachment-modal.phtml");?>
<!-- [End] LibAttachment: Modal Form -->


<script type="text/javascript">

	var theme = "source/lib-attachment";

	$(document).ready(function() {
		$("#navLibAttachment").addClass("active");
		searchHandler["srch-libAttachment"] = {
				action: theme + "/lib-attachment-grid",
				container: "LibAttachmentGrid"
		};
    searchStack["srch-libAttachment"] = wrapFunction(search, this, ["srch-libAttachment"]);
	});

	function addLibAttachment(id) {
		//$("#libAttachmentModalHeading").html("Add New Lib Attachment");
		mode = "create";
		clearForm("libAttachment", "modalLibAttachment");
	}

	function editLibAttachment(id) {
		//$("#libAttachmentModalHeading").html("Edit Lib Attachment");
		mode = "update";
		populateForm("libAttachment", "lib_attachment", libAttachmentData[id], "modalLibAttachment");
	}

</script>