<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibAttachmentGrid",
		"lib-attachment-grid",
		$this->result["LibAttachment"]["Paging"]["CurrentPage"],
		$this->result["LibAttachment"]["Paging"]["TotalPages"],
		$this->result["LibAttachment"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibAttachment"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Filename</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_attachment.filename" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAttachment', 'lib_attachment.filename', 'asc');"></i>
							<i class="icon-<?php echo "lib_attachment.filename" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAttachment', 'lib_attachment.filename', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Document</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_attachment.document" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAttachment', 'lib_attachment.document', 'asc');"></i>
							<i class="icon-<?php echo "lib_attachment.document" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAttachment', 'lib_attachment.document', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mime Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_attachment.mime_type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAttachment', 'lib_attachment.mime_type', 'asc');"></i>
							<i class="icon-<?php echo "lib_attachment.mime_type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAttachment', 'lib_attachment.mime_type', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibAttachment();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAttachment_lib_attachment.filename" type="text" class="span12 srch-libAttachment"
						value="<?php echo isset($this->result['LibAttachment']['Search']['lib_attachment.filename']) ? $this->result['LibAttachment']['Search']['lib_attachment.filename'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAttachment_lib_attachment.document" type="text" class="span12 srch-libAttachment"
						value="<?php echo isset($this->result['LibAttachment']['Search']['lib_attachment.document']) ? $this->result['LibAttachment']['Search']['lib_attachment.document'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libAttachment_lib_attachment.mime_type" type="text" class="span12 srch-libAttachment"
						value="<?php echo isset($this->result['LibAttachment']['Search']['lib_attachment.mime_type']) ? $this->result['LibAttachment']['Search']['lib_attachment.mime_type'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libAttachment');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibAttachment"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["filename"]; ?></td>
					<td><?php echo $record["document"]; ?></td>
					<td><?php echo $record["mime_type"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibAttachment(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibAttachment"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libAttachmentData = <?php echo Zend_Json::encode($this->data["LibAttachment"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libAttachment"]();
		});
		$(".srch-libAttachment").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libAttachment"]();
		    }
		});
	});
	
</script>