<!-- LibAttachment: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibAttachment">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libAttachmentModalHeading">Edit Lib Attachment</h3>
	  </div>
		<form id="libAttachmentForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libAttachment_filename"><b>Filename *</b></label>
						<input id="libAttachment_filename" name="filename" type="text"
							form-id="libAttachment" class="span12 required" maxlength="100">
					</div>
		  		<div class="control-group">
		    		<label for="libAttachment_mime_type"><b>Mime Type</b></label>
						<input id="libAttachment_mime_type" name="mime_type" type="text"
							form-id="libAttachment" class="span12 " maxlength="200">
					</div>
				<input type="hidden" id="libAttachment_id" name="id" form-id="libAttachment">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibAttachment: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libAttachmentForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libAttachment", "libAttachment", "api/data/" + mode,
			  	"LibAttachmentGrid", theme + "/lib-attachment-grid",
					false, true, false, {});
		  }
		});
	});
</script>