<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"OwnerGrid",
		"owner-grid",
		$this->result["Owner"]["Paging"]["CurrentPage"],
		$this->result["Owner"]["Paging"]["TotalPages"],
		$this->result["Owner"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Owner"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "owner.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('owner', 'owner.name', 'asc');"></i>
							<i class="icon-<?php echo "owner.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('owner', 'owner.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "owner.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('owner', 'owner.created', 'asc');"></i>
							<i class="icon-<?php echo "owner.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('owner', 'owner.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "owner.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('owner', 'owner.updated', 'asc');"></i>
							<i class="icon-<?php echo "owner.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('owner', 'owner.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addOwner();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_owner_owner.name" type="text" class="span12 srch-owner"
						value="<?php echo isset($this->result['Owner']['Search']['owner.name']) ? $this->result['Owner']['Search']['owner.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_owner_owner.created" type="text" class="span12 srch-owner"
						value="<?php echo isset($this->result['Owner']['Search']['owner.created']) ? $this->result['Owner']['Search']['owner.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_owner_owner.updated" type="text" class="span12 srch-owner"
						value="<?php echo isset($this->result['Owner']['Search']['owner.updated']) ? $this->result['Owner']['Search']['owner.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-owner');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Owner"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editOwner(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Owner"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var ownerData = <?php echo Zend_Json::encode($this->data["Owner"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-owner"]();
		});
		$(".srch-owner").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-owner"]();
		    }
		});
	});
	
</script>