<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"BillInvoiceLineItemGrid",
		"bill-invoice-line-item-grid",
		$this->result["BillInvoiceLineItem"]["Paging"]["CurrentPage"],
		$this->result["BillInvoiceLineItem"]["Paging"]["TotalPages"],
		$this->result["BillInvoiceLineItem"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["BillInvoiceLineItem"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Bill Invoice</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice_line_item.invoice_nr" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.invoice_nr', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice_line_item.invoice_nr" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.invoice_nr', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Lib Service</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice_line_item.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.name', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice_line_item.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Description</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice_line_item.description" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.description', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice_line_item.description" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.description', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Units</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice_line_item.units" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.units', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice_line_item.units" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.units', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Months</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice_line_item.months" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.months', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice_line_item.months" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoiceLineItem', 'bill_invoice_line_item.months', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addBillInvoiceLineItem();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoiceLineItem_bill_invoice.invoice_nr" type="text" class="span12 srch-billInvoiceLineItem"
						value="<?php echo isset($this->result['BillInvoiceLineItem']['Search']['bill_invoice.invoice_nr']) ? $this->result['BillInvoiceLineItem']['Search']['bill_invoice.invoice_nr'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoiceLineItem_lib_service.name" type="text" class="span12 srch-billInvoiceLineItem"
						value="<?php echo isset($this->result['BillInvoiceLineItem']['Search']['lib_service.name']) ? $this->result['BillInvoiceLineItem']['Search']['lib_service.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoiceLineItem_bill_invoice_line_item.description" type="text" class="span12 srch-billInvoiceLineItem"
						value="<?php echo isset($this->result['BillInvoiceLineItem']['Search']['bill_invoice_line_item.description']) ? $this->result['BillInvoiceLineItem']['Search']['bill_invoice_line_item.description'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoiceLineItem_bill_invoice_line_item.units" type="text" class="span12 srch-billInvoiceLineItem"
						value="<?php echo isset($this->result['BillInvoiceLineItem']['Search']['bill_invoice_line_item.units']) ? $this->result['BillInvoiceLineItem']['Search']['bill_invoice_line_item.units'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoiceLineItem_bill_invoice_line_item.months" type="text" class="span12 srch-billInvoiceLineItem"
						value="<?php echo isset($this->result['BillInvoiceLineItem']['Search']['bill_invoice_line_item.months']) ? $this->result['BillInvoiceLineItem']['Search']['bill_invoice_line_item.months'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-billInvoiceLineItem');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["BillInvoiceLineItem"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["bill_invoice_invoice_nr"]; ?></td>
					<td><?php echo $record["lib_service_name"]; ?></td>
					<td><?php echo $record["description"]; ?></td>
					<td><?php echo $record["units"]; ?></td>
					<td><?php echo $record["months"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editBillInvoiceLineItem(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["BillInvoiceLineItem"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var billInvoiceLineItemData = <?php echo Zend_Json::encode($this->data["BillInvoiceLineItem"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-billInvoiceLineItem"]();
		});
		$(".srch-billInvoiceLineItem").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-billInvoiceLineItem"]();
		    }
		});
	});
	
</script>