
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- BillInvoiceLineItem: Data Grid -->
<span id="BillInvoiceLineItemGrid">
<?php include_once("bill-invoice-line-item-grid.phtml");?>
</span>
<!-- [End] BillInvoiceLineItem: Data Grid -->

<!-- BillInvoiceLineItem: Modal Form -->
<?php include_once("bill-invoice-line-item-modal.phtml");?>
<!-- [End] BillInvoiceLineItem: Modal Form -->


<script type="text/javascript">

	var theme = "source/bill-invoice-line-item";

	$(document).ready(function() {
		$("#navBillInvoiceLineItem").addClass("active");
		searchHandler["srch-billInvoiceLineItem"] = {
				action: theme + "/bill-invoice-line-item-grid",
				container: "BillInvoiceLineItemGrid"
		};
    searchStack["srch-billInvoiceLineItem"] = wrapFunction(search, this, ["srch-billInvoiceLineItem"]);
	});

	function addBillInvoiceLineItem(id) {
		//$("#billInvoiceLineItemModalHeading").html("Add New Bill Invoice Line Item");
		mode = "create";
		clearForm("billInvoiceLineItem", "modalBillInvoiceLineItem");
	}

	function editBillInvoiceLineItem(id) {
		//$("#billInvoiceLineItemModalHeading").html("Edit Bill Invoice Line Item");
		mode = "update";
		populateForm("billInvoiceLineItem", "bill_invoice_line_item", billInvoiceLineItemData[id], "modalBillInvoiceLineItem");
	}

</script>