
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- StreetLightType: Data Grid -->
<span id="StreetLightTypeGrid">
<?php include_once("street-light-type-grid.phtml");?>
</span>
<!-- [End] StreetLightType: Data Grid -->

<!-- StreetLightType: Modal Form -->
<?php include_once("street-light-type-modal.phtml");?>
<!-- [End] StreetLightType: Modal Form -->


<script type="text/javascript">

	var theme = "source/street-light-type";

	$(document).ready(function() {
		$("#navStreetLightType").addClass("active");
		searchHandler["srch-streetLightType"] = {
				action: theme + "/street-light-type-grid",
				container: "StreetLightTypeGrid"
		};
    searchStack["srch-streetLightType"] = wrapFunction(search, this, ["srch-streetLightType"]);
	});

	function addStreetLightType(id) {
		//$("#streetLightTypeModalHeading").html("Add New Street Light Type");
		mode = "create";
		clearForm("streetLightType", "modalStreetLightType");
	}

	function editStreetLightType(id) {
		//$("#streetLightTypeModalHeading").html("Edit Street Light Type");
		mode = "update";
		populateForm("streetLightType", "street_light_type", streetLightTypeData[id], "modalStreetLightType");
	}

</script>