<!-- StreetLightType: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalStreetLightType">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="streetLightTypeModalHeading">Edit Street Light Type</h3>
	  </div>
		<form id="streetLightTypeForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="streetLightType_name"><b>Name *</b></label>
						<input id="streetLightType_name" name="name" type="text"
							form-id="streetLightType" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="streetLightType_id" name="id" form-id="streetLightType">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] StreetLightType: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#streetLightTypeForm").validate({
		  submitHandler: function(form) {
			  doUpdate("streetLightType", "streetLightType", "api/data/" + mode,
			  	"StreetLightTypeGrid", theme + "/street-light-type-grid",
					false, true, false, {});
		  }
		});
	});
</script>