<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"StreetLightTypeGrid",
		"street-light-type-grid",
		$this->result["StreetLightType"]["Paging"]["CurrentPage"],
		$this->result["StreetLightType"]["Paging"]["TotalPages"],
		$this->result["StreetLightType"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["StreetLightType"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street_light_type.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('streetLightType', 'street_light_type.name', 'asc');"></i>
							<i class="icon-<?php echo "street_light_type.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('streetLightType', 'street_light_type.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street_light_type.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('streetLightType', 'street_light_type.created', 'asc');"></i>
							<i class="icon-<?php echo "street_light_type.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('streetLightType', 'street_light_type.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street_light_type.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('streetLightType', 'street_light_type.updated', 'asc');"></i>
							<i class="icon-<?php echo "street_light_type.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('streetLightType', 'street_light_type.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addStreetLightType();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_streetLightType_street_light_type.name" type="text" class="span12 srch-streetLightType"
						value="<?php echo isset($this->result['StreetLightType']['Search']['street_light_type.name']) ? $this->result['StreetLightType']['Search']['street_light_type.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_streetLightType_street_light_type.created" type="text" class="span12 srch-streetLightType"
						value="<?php echo isset($this->result['StreetLightType']['Search']['street_light_type.created']) ? $this->result['StreetLightType']['Search']['street_light_type.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_streetLightType_street_light_type.updated" type="text" class="span12 srch-streetLightType"
						value="<?php echo isset($this->result['StreetLightType']['Search']['street_light_type.updated']) ? $this->result['StreetLightType']['Search']['street_light_type.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-streetLightType');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["StreetLightType"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editStreetLightType(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["StreetLightType"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var streetLightTypeData = <?php echo Zend_Json::encode($this->data["StreetLightType"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-streetLightType"]();
		});
		$(".srch-streetLightType").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-streetLightType"]();
		    }
		});
	});
	
</script>