<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AppAuditLogGrid",
		"app-audit-log-grid",
		$this->result["AppAuditLog"]["Paging"]["CurrentPage"],
		$this->result["AppAuditLog"]["Paging"]["TotalPages"],
		$this->result["AppAuditLog"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["AppAuditLog"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Customer Context</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_audit_log.customer_context" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appAuditLog', 'app_audit_log.customer_context', 'asc');"></i>
							<i class="icon-<?php echo "app_audit_log.customer_context" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appAuditLog', 'app_audit_log.customer_context', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Action</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_audit_log.action" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appAuditLog', 'app_audit_log.action', 'asc');"></i>
							<i class="icon-<?php echo "app_audit_log.action" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appAuditLog', 'app_audit_log.action', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Table Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_audit_log.table_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appAuditLog', 'app_audit_log.table_name', 'asc');"></i>
							<i class="icon-<?php echo "app_audit_log.table_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appAuditLog', 'app_audit_log.table_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_audit_log.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appAuditLog', 'app_audit_log.created', 'asc');"></i>
							<i class="icon-<?php echo "app_audit_log.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appAuditLog', 'app_audit_log.created', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAppAuditLog();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appAuditLog_app_audit_log.customer_context" type="text" class="span12 srch-appAuditLog"
						value="<?php echo isset($this->result['AppAuditLog']['Search']['app_audit_log.customer_context']) ? $this->result['AppAuditLog']['Search']['app_audit_log.customer_context'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appAuditLog_app_audit_log.action" type="text" class="span12 srch-appAuditLog"
						value="<?php echo isset($this->result['AppAuditLog']['Search']['app_audit_log.action']) ? $this->result['AppAuditLog']['Search']['app_audit_log.action'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appAuditLog_app_audit_log.table_name" type="text" class="span12 srch-appAuditLog"
						value="<?php echo isset($this->result['AppAuditLog']['Search']['app_audit_log.table_name']) ? $this->result['AppAuditLog']['Search']['app_audit_log.table_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appAuditLog_app_audit_log.created" type="text" class="span12 srch-appAuditLog"
						value="<?php echo isset($this->result['AppAuditLog']['Search']['app_audit_log.created']) ? $this->result['AppAuditLog']['Search']['app_audit_log.created'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-appAuditLog');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["AppAuditLog"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["customer_context"]; ?></td>
					<td><?php echo $record["action"]; ?></td>
					<td><?php echo $record["table_name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAppAuditLog(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["AppAuditLog"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var appAuditLogData = <?php echo Zend_Json::encode($this->data["AppAuditLog"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-appAuditLog"]();
		});
		$(".srch-appAuditLog").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-appAuditLog"]();
		    }
		});
	});

</script>