
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- LibXmlrpcProfile: Data Grid -->
<span id="LibXmlrpcProfileGrid">
<?php include_once("lib-xmlrpc-profile-grid.phtml");?>
</span>
<!-- [End] LibXmlrpcProfile: Data Grid -->

<!-- LibXmlrpcProfile: Modal Form -->
<?php include_once("lib-xmlrpc-profile-modal.phtml");?>
<!-- [End] LibXmlrpcProfile: Modal Form -->


<script type="text/javascript">

	var theme = "source/lib-xmlrpc-profile";

	$(document).ready(function() {
		$("#navLibXmlrpcProfile").addClass("active");
		searchHandler["srch-libXmlrpcProfile"] = {
				action: theme + "/lib-xmlrpc-profile-grid",
				container: "LibXmlrpcProfileGrid"
		};
    searchStack["srch-libXmlrpcProfile"] = wrapFunction(search, this, ["srch-libXmlrpcProfile"]);
	});

	function addLibXmlrpcProfile(id) {
		//$("#libXmlrpcProfileModalHeading").html("Add New Lib Xmlrpc Profile");
		mode = "create";
		clearForm("libXmlrpcProfile", "modalLibXmlrpcProfile");
	}

	function editLibXmlrpcProfile(id) {
		//$("#libXmlrpcProfileModalHeading").html("Edit Lib Xmlrpc Profile");
		mode = "update";
		populateForm("libXmlrpcProfile", "lib_xmlrpc_profile", libXmlrpcProfileData[id], "modalLibXmlrpcProfile");
	}

</script>