<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibXmlrpcProfileGrid",
		"lib-xmlrpc-profile-grid",
		$this->result["LibXmlrpcProfile"]["Paging"]["CurrentPage"],
		$this->result["LibXmlrpcProfile"]["Paging"]["TotalPages"],
		$this->result["LibXmlrpcProfile"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibXmlrpcProfile"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_xmlrpc_profile.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_xmlrpc_profile.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Auth Token</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_xmlrpc_profile.auth_token" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.auth_token', 'asc');"></i>
							<i class="icon-<?php echo "lib_xmlrpc_profile.auth_token" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.auth_token', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Requests</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_xmlrpc_profile.requests" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.requests', 'asc');"></i>
							<i class="icon-<?php echo "lib_xmlrpc_profile.requests" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.requests', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_xmlrpc_profile.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.created', 'asc');"></i>
							<i class="icon-<?php echo "lib_xmlrpc_profile.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_xmlrpc_profile.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.updated', 'asc');"></i>
							<i class="icon-<?php echo "lib_xmlrpc_profile.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libXmlrpcProfile', 'lib_xmlrpc_profile.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibXmlrpcProfile();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libXmlrpcProfile_lib_xmlrpc_profile.name" type="text" class="span12 srch-libXmlrpcProfile"
						value="<?php echo isset($this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.name']) ? $this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libXmlrpcProfile_lib_xmlrpc_profile.auth_token" type="text" class="span12 srch-libXmlrpcProfile"
						value="<?php echo isset($this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.auth_token']) ? $this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.auth_token'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libXmlrpcProfile_lib_xmlrpc_profile.requests" type="text" class="span12 srch-libXmlrpcProfile"
						value="<?php echo isset($this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.requests']) ? $this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.requests'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libXmlrpcProfile_lib_xmlrpc_profile.created" type="text" class="span12 srch-libXmlrpcProfile"
						value="<?php echo isset($this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.created']) ? $this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libXmlrpcProfile_lib_xmlrpc_profile.updated" type="text" class="span12 srch-libXmlrpcProfile"
						value="<?php echo isset($this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.updated']) ? $this->result['LibXmlrpcProfile']['Search']['lib_xmlrpc_profile.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libXmlrpcProfile');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibXmlrpcProfile"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["auth_token"]; ?></td>
					<td><?php echo $record["requests"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibXmlrpcProfile(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibXmlrpcProfile"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libXmlrpcProfileData = <?php echo Zend_Json::encode($this->data["LibXmlrpcProfile"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libXmlrpcProfile"]();
		});
		$(".srch-libXmlrpcProfile").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libXmlrpcProfile"]();
		    }
		});
	});
	
</script>