<!-- LibXmlrpcProfile: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibXmlrpcProfile">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libXmlrpcProfileModalHeading">Edit Lib Xmlrpc Profile</h3>
	  </div>
		<form id="libXmlrpcProfileForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libXmlrpcProfile_name"><b>Name *</b></label>
						<input id="libXmlrpcProfile_name" name="name" type="text"
							form-id="libXmlrpcProfile" class="span12 required" maxlength="50">
					</div>
		  		<div class="control-group">
		    		<label for="libXmlrpcProfile_auth_token"><b>Auth Token *</b></label>
						<input id="libXmlrpcProfile_auth_token" name="auth_token" type="text"
							form-id="libXmlrpcProfile" class="span10 required" maxlength="40">
					</div>
		  		<div class="control-group">
		    		<label for="libXmlrpcProfile_requests"><b>Requests</b></label>
						<input id="libXmlrpcProfile_requests" name="requests" type="text"
							form-id="libXmlrpcProfile" class="span4  digits" >
					</div>
				<input type="hidden" id="libXmlrpcProfile_id" name="id" form-id="libXmlrpcProfile">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibXmlrpcProfile: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libXmlrpcProfileForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libXmlrpcProfile", "libXmlrpcProfile", "api/data/" + mode,
			  	"LibXmlrpcProfileGrid", theme + "/lib-xmlrpc-profile-grid",
					false, true, false, {});
		  }
		});
	});
</script>