
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- LibAuthenticationLog: Data Grid -->
<span id="LibAuthenticationLogGrid">
<?php include_once("lib-authentication-log-grid.phtml");?>
</span>
<!-- [End] LibAuthenticationLog: Data Grid -->

<!-- LibAuthenticationLog: Modal Form -->
<?php include_once("lib-authentication-log-modal.phtml");?>
<!-- [End] LibAuthenticationLog: Modal Form -->


<script type="text/javascript">

	var theme = "source/lib-authentication-log";

	$(document).ready(function() {
		$("#navLibAuthenticationLog").addClass("active");
		searchHandler["srch-libAuthenticationLog"] = {
				action: theme + "/lib-authentication-log-grid",
				container: "LibAuthenticationLogGrid"
		};
    searchStack["srch-libAuthenticationLog"] = wrapFunction(search, this, ["srch-libAuthenticationLog"]);
	});

	function addLibAuthenticationLog(id) {
		//$("#libAuthenticationLogModalHeading").html("Add New Lib Authentication Log");
		mode = "create";
		clearForm("libAuthenticationLog", "modalLibAuthenticationLog");
	}

	function editLibAuthenticationLog(id) {
		//$("#libAuthenticationLogModalHeading").html("Edit Lib Authentication Log");
		mode = "update";
		populateForm("libAuthenticationLog", "lib_authentication_log", libAuthenticationLogData[id], "modalLibAuthenticationLog");
	}

</script>