<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibAuthenticationLogGrid",
		"lib-authentication-log-grid",
		$this->result["LibAuthenticationLog"]["Paging"]["CurrentPage"],
		$this->result["LibAuthenticationLog"]["Paging"]["TotalPages"],
		$this->result["LibAuthenticationLog"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibAuthenticationLog"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Ip Address</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_authentication_log.ip_address" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAuthenticationLog', 'lib_authentication_log.ip_address', 'asc');"></i>
							<i class="icon-<?php echo "lib_authentication_log.ip_address" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAuthenticationLog', 'lib_authentication_log.ip_address', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Profile</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_authentication_log.first_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAuthenticationLog', 'lib_authentication_log.first_name', 'asc');"></i>
							<i class="icon-<?php echo "lib_authentication_log.first_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAuthenticationLog', 'lib_authentication_log.first_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_authentication_log.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libAuthenticationLog', 'lib_authentication_log.created', 'asc');"></i>
							<i class="icon-<?php echo "lib_authentication_log.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libAuthenticationLog', 'lib_authentication_log.created', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibAuthenticationLog();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libAuthenticationLog_lib_authentication_log.ip_address" type="text" class="span12 srch-libAuthenticationLog"
						value="<?php echo isset($this->result['LibAuthenticationLog']['Search']['lib_authentication_log.ip_address']) ? $this->result['LibAuthenticationLog']['Search']['lib_authentication_log.ip_address'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libAuthenticationLog_profile.first_name" type="text" class="span12 srch-libAuthenticationLog"
						value="<?php echo isset($this->result['LibAuthenticationLog']['Search']['profile.first_name']) ? $this->result['LibAuthenticationLog']['Search']['profile.first_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libAuthenticationLog_lib_authentication_log.created" type="text" class="span12 srch-libAuthenticationLog"
						value="<?php echo isset($this->result['LibAuthenticationLog']['Search']['lib_authentication_log.created']) ? $this->result['LibAuthenticationLog']['Search']['lib_authentication_log.created'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libAuthenticationLog');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibAuthenticationLog"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["ip_address"]; ?></td>
					<td><?php echo $record["profile_first_name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibAuthenticationLog(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibAuthenticationLog"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libAuthenticationLogData = <?php echo Zend_Json::encode($this->data["LibAuthenticationLog"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libAuthenticationLog"]();
		});
		$(".srch-libAuthenticationLog").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libAuthenticationLog"]();
		    }
		});
	});

</script>