<!-- LibAuthenticationLog: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibAuthenticationLog">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libAuthenticationLogModalHeading">Edit Lib Authentication Log</h3>
	  </div>
		<form id="libAuthenticationLogForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libAuthenticationLog_ip_address"><b>Ip Address *</b></label>
						<input id="libAuthenticationLog_ip_address" name="ip_address" type="text"
							form-id="libAuthenticationLog" class="span12 required" maxlength="50">
					</div>
		  		<div class="control-group">
				  	<label for="libAuthenticationLog_profile_id"><b>Profile</b></label>
						<select id="libAuthenticationLog_profile_id" name="profile_id"
							form-id="libAuthenticationLog" class="span12 " >
							<option value="">-- Select Profile --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listProfile"], false); ?>

						</select>
					</div>
				<input type="hidden" id="libAuthenticationLog_id" name="id" form-id="libAuthenticationLog">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibAuthenticationLog: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libAuthenticationLogForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libAuthenticationLog", "libAuthenticationLog", "api/data/" + mode,
			  	"LibAuthenticationLogGrid", theme + "/lib-authentication-log-grid",
					false, true, false, {});
		  }
		});
	});
</script>