<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibRegionGrid",
		"lib-region-grid",
		$this->result["LibRegion"]["Paging"]["CurrentPage"],
		$this->result["LibRegion"]["Paging"]["TotalPages"],
		$this->result["LibRegion"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibRegion"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Lib Country</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_region.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libRegion', 'lib_region.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_region.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libRegion', 'lib_region.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_region.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libRegion', 'lib_region.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_region.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libRegion', 'lib_region.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Iso3166_2 Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_region.iso3166_2_code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libRegion', 'lib_region.iso3166_2_code', 'asc');"></i>
							<i class="icon-<?php echo "lib_region.iso3166_2_code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libRegion', 'lib_region.iso3166_2_code', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Fips10_4 Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_region.fips10_4_code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libRegion', 'lib_region.fips10_4_code', 'asc');"></i>
							<i class="icon-<?php echo "lib_region.fips10_4_code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libRegion', 'lib_region.fips10_4_code', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibRegion();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libRegion_lib_country.name" type="text" class="span12 srch-libRegion"
						value="<?php echo isset($this->result['LibRegion']['Search']['lib_country.name']) ? $this->result['LibRegion']['Search']['lib_country.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libRegion_lib_region.name" type="text" class="span12 srch-libRegion"
						value="<?php echo isset($this->result['LibRegion']['Search']['lib_region.name']) ? $this->result['LibRegion']['Search']['lib_region.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libRegion_lib_region.iso3166_2_code" type="text" class="span12 srch-libRegion"
						value="<?php echo isset($this->result['LibRegion']['Search']['lib_region.iso3166_2_code']) ? $this->result['LibRegion']['Search']['lib_region.iso3166_2_code'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libRegion_lib_region.fips10_4_code" type="text" class="span12 srch-libRegion"
						value="<?php echo isset($this->result['LibRegion']['Search']['lib_region.fips10_4_code']) ? $this->result['LibRegion']['Search']['lib_region.fips10_4_code'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libRegion');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibRegion"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["lib_country_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["iso3166_2_code"]; ?></td>
					<td><?php echo $record["fips10_4_code"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibRegion(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibRegion"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libRegionData = <?php echo Zend_Json::encode($this->data["LibRegion"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libRegion"]();
		});
		$(".srch-libRegion").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libRegion"]();
		    }
		});
	});
	
</script>