
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- Material: Data Grid -->
<span id="MaterialGrid">
<?php include_once("material-grid.phtml");?>
</span>
<!-- [End] Material: Data Grid -->

<!-- Material: Modal Form -->
<?php include_once("material-modal.phtml");?>
<!-- [End] Material: Modal Form -->


<script type="text/javascript">

	var theme = "source/material";

	$(document).ready(function() {
		$("#navMaterial").addClass("active");
		searchHandler["srch-material"] = {
				action: theme + "/material-grid",
				container: "MaterialGrid"
		};
    searchStack["srch-material"] = wrapFunction(search, this, ["srch-material"]);
	});

	function addMaterial(id) {
		//$("#materialModalHeading").html("Add New Material");
		mode = "create";
		clearForm("material", "modalMaterial");
	}

	function editMaterial(id) {
		//$("#materialModalHeading").html("Edit Material");
		mode = "update";
		populateForm("material", "material", materialData[id], "modalMaterial");
	}

</script>