<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"MaterialGrid",
		"material-grid",
		$this->result["Material"]["Paging"]["CurrentPage"],
		$this->result["Material"]["Paging"]["TotalPages"],
		$this->result["Material"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Material"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "material.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('material', 'material.name', 'asc');"></i>
							<i class="icon-<?php echo "material.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('material', 'material.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "material.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('material', 'material.created', 'asc');"></i>
							<i class="icon-<?php echo "material.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('material', 'material.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "material.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('material', 'material.updated', 'asc');"></i>
							<i class="icon-<?php echo "material.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('material', 'material.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addMaterial();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_material_material.name" type="text" class="span12 srch-material"
						value="<?php echo isset($this->result['Material']['Search']['material.name']) ? $this->result['Material']['Search']['material.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_material_material.created" type="text" class="span12 srch-material"
						value="<?php echo isset($this->result['Material']['Search']['material.created']) ? $this->result['Material']['Search']['material.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_material_material.updated" type="text" class="span12 srch-material"
						value="<?php echo isset($this->result['Material']['Search']['material.updated']) ? $this->result['Material']['Search']['material.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-material');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Material"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editMaterial(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Material"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var materialData = <?php echo Zend_Json::encode($this->data["Material"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-material"]();
		});
		$(".srch-material").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-material"]();
		    }
		});
	});
	
</script>