<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibNewsletterGrid",
		"lib-newsletter-grid",
		$this->result["LibNewsletter"]["Paging"]["CurrentPage"],
		$this->result["LibNewsletter"]["Paging"]["TotalPages"],
		$this->result["LibNewsletter"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibNewsletter"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Lib Newsletter Template</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletter', 'lib_newsletter.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletter', 'lib_newsletter.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Subject</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter.subject" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletter', 'lib_newsletter.subject', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter.subject" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletter', 'lib_newsletter.subject', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Lib Attachment</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter.filename" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletter', 'lib_newsletter.filename', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter.filename" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletter', 'lib_newsletter.filename', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Status</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter.status" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletter', 'lib_newsletter.status', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter.status" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletter', 'lib_newsletter.status', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Sent To</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_newsletter.sent_to" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNewsletter', 'lib_newsletter.sent_to', 'asc');"></i>
							<i class="icon-<?php echo "lib_newsletter.sent_to" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNewsletter', 'lib_newsletter.sent_to', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibNewsletter();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletter_lib_newsletter_template.name" type="text" class="span12 srch-libNewsletter"
						value="<?php echo isset($this->result['LibNewsletter']['Search']['lib_newsletter_template.name']) ? $this->result['LibNewsletter']['Search']['lib_newsletter_template.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletter_lib_newsletter.subject" type="text" class="span12 srch-libNewsletter"
						value="<?php echo isset($this->result['LibNewsletter']['Search']['lib_newsletter.subject']) ? $this->result['LibNewsletter']['Search']['lib_newsletter.subject'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletter_lib_attachment.filename" type="text" class="span12 srch-libNewsletter"
						value="<?php echo isset($this->result['LibNewsletter']['Search']['lib_attachment.filename']) ? $this->result['LibNewsletter']['Search']['lib_attachment.filename'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletter_lib_newsletter.status" type="text" class="span12 srch-libNewsletter"
						value="<?php echo isset($this->result['LibNewsletter']['Search']['lib_newsletter.status']) ? $this->result['LibNewsletter']['Search']['lib_newsletter.status'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libNewsletter_lib_newsletter.sent_to" type="text" class="span12 srch-libNewsletter"
						value="<?php echo isset($this->result['LibNewsletter']['Search']['lib_newsletter.sent_to']) ? $this->result['LibNewsletter']['Search']['lib_newsletter.sent_to'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libNewsletter');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibNewsletter"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["lib_newsletter_template_name"]; ?></td>
					<td><?php echo $record["subject"]; ?></td>
					<td><?php echo $record["lib_attachment_filename"]; ?></td>
					<td><?php echo $record["status"]; ?></td>
					<td><?php echo $record["sent_to"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibNewsletter(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibNewsletter"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libNewsletterData = <?php echo Zend_Json::encode($this->data["LibNewsletter"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libNewsletter"]();
		});
		$(".srch-libNewsletter").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libNewsletter"]();
		    }
		});
	});
	
</script>