<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibIpCountryGrid",
		"lib-ip-country-grid",
		$this->result["LibIpCountry"]["Paging"]["CurrentPage"],
		$this->result["LibIpCountry"]["Paging"]["TotalPages"],
		$this->result["LibIpCountry"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibIpCountry"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Ip From</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_ip_country.ip_from" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libIpCountry', 'lib_ip_country.ip_from', 'asc');"></i>
							<i class="icon-<?php echo "lib_ip_country.ip_from" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libIpCountry', 'lib_ip_country.ip_from', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Ip To</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_ip_country.ip_to" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libIpCountry', 'lib_ip_country.ip_to', 'asc');"></i>
							<i class="icon-<?php echo "lib_ip_country.ip_to" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libIpCountry', 'lib_ip_country.ip_to', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Provider</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_ip_country.provider" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libIpCountry', 'lib_ip_country.provider', 'asc');"></i>
							<i class="icon-<?php echo "lib_ip_country.provider" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libIpCountry', 'lib_ip_country.provider', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Assigned</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_ip_country.assigned" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libIpCountry', 'lib_ip_country.assigned', 'asc');"></i>
							<i class="icon-<?php echo "lib_ip_country.assigned" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libIpCountry', 'lib_ip_country.assigned', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Country Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_ip_country.country_code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libIpCountry', 'lib_ip_country.country_code', 'asc');"></i>
							<i class="icon-<?php echo "lib_ip_country.country_code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libIpCountry', 'lib_ip_country.country_code', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibIpCountry();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libIpCountry_lib_ip_country.ip_from" type="text" class="span12 srch-libIpCountry"
						value="<?php echo isset($this->result['LibIpCountry']['Search']['lib_ip_country.ip_from']) ? $this->result['LibIpCountry']['Search']['lib_ip_country.ip_from'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libIpCountry_lib_ip_country.ip_to" type="text" class="span12 srch-libIpCountry"
						value="<?php echo isset($this->result['LibIpCountry']['Search']['lib_ip_country.ip_to']) ? $this->result['LibIpCountry']['Search']['lib_ip_country.ip_to'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libIpCountry_lib_ip_country.provider" type="text" class="span12 srch-libIpCountry"
						value="<?php echo isset($this->result['LibIpCountry']['Search']['lib_ip_country.provider']) ? $this->result['LibIpCountry']['Search']['lib_ip_country.provider'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libIpCountry_lib_ip_country.assigned" type="text" class="span12 srch-libIpCountry"
						value="<?php echo isset($this->result['LibIpCountry']['Search']['lib_ip_country.assigned']) ? $this->result['LibIpCountry']['Search']['lib_ip_country.assigned'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libIpCountry_lib_ip_country.country_code" type="text" class="span12 srch-libIpCountry"
						value="<?php echo isset($this->result['LibIpCountry']['Search']['lib_ip_country.country_code']) ? $this->result['LibIpCountry']['Search']['lib_ip_country.country_code'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libIpCountry');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibIpCountry"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["ip_from"]; ?></td>
					<td><?php echo $record["ip_to"]; ?></td>
					<td><?php echo $record["provider"]; ?></td>
					<td><?php echo $record["assigned"]; ?></td>
					<td><?php echo $record["country_code"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibIpCountry(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibIpCountry"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libIpCountryData = <?php echo Zend_Json::encode($this->data["LibIpCountry"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libIpCountry"]();
		});
		$(".srch-libIpCountry").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libIpCountry"]();
		    }
		});
	});
	
</script>