<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibCityGrid",
		"lib-city-grid",
		$this->result["LibCity"]["Paging"]["CurrentPage"],
		$this->result["LibCity"]["Paging"]["TotalPages"],
		$this->result["LibCity"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibCity"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Lib Region</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_city.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCity', 'lib_city.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_city.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCity', 'lib_city.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_city.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCity', 'lib_city.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_city.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCity', 'lib_city.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Latitude</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_city.latitude" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCity', 'lib_city.latitude', 'asc');"></i>
							<i class="icon-<?php echo "lib_city.latitude" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCity', 'lib_city.latitude', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Longitude</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_city.longitude" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCity', 'lib_city.longitude', 'asc');"></i>
							<i class="icon-<?php echo "lib_city.longitude" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCity', 'lib_city.longitude', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibCity();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCity_lib_region.name" type="text" class="span12 srch-libCity"
						value="<?php echo isset($this->result['LibCity']['Search']['lib_region.name']) ? $this->result['LibCity']['Search']['lib_region.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCity_lib_city.name" type="text" class="span12 srch-libCity"
						value="<?php echo isset($this->result['LibCity']['Search']['lib_city.name']) ? $this->result['LibCity']['Search']['lib_city.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCity_lib_city.latitude" type="text" class="span12 srch-libCity"
						value="<?php echo isset($this->result['LibCity']['Search']['lib_city.latitude']) ? $this->result['LibCity']['Search']['lib_city.latitude'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCity_lib_city.longitude" type="text" class="span12 srch-libCity"
						value="<?php echo isset($this->result['LibCity']['Search']['lib_city.longitude']) ? $this->result['LibCity']['Search']['lib_city.longitude'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libCity');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibCity"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["lib_region_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["latitude"]; ?></td>
					<td><?php echo $record["longitude"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibCity(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibCity"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libCityData = <?php echo Zend_Json::encode($this->data["LibCity"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libCity"]();
		});
		$(".srch-libCity").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libCity"]();
		    }
		});
	});
	
</script>