<!-- LibCity: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibCity">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libCityModalHeading">Edit Lib City</h3>
	  </div>
		<form id="libCityForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="libCity_lib_country_id"><b>Lib Country</b></label>
						<select id="libCity_lib_country_id" name="lib_country_id"
							form-id="libCity" class="span12 data-dependant-parent required" 
							data='{"dependant":"libCity_lib_region_id","item":"Lib Region","title":"Lib Country","filterField":"lib_country_id"}'>
							<option value="">-- Select Lib Country --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listLibCountry"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
				  	<label for="libCity_lib_region_id"><b>Lib Region</b></label>
						<select id="libCity_lib_region_id" name="lib_region_id"
							form-id="libCity" class="span12 data-dependant-child required" 
							data='{"parent":"libCity_lib_country_id"}'>
							<option value="">--- Select Lib Country ---</option>
							
						</select>
					</div>
		  		<div class="control-group">
		    		<label for="libCity_name"><b>Name *</b></label>
						<input id="libCity_name" name="name" type="text"
							form-id="libCity" class="span12 required" maxlength="100">
					</div>
		  		<div class="control-group">
		    		<label for="libCity_latitude"><b>Latitude</b></label>
						<input id="libCity_latitude" name="latitude" type="text"
							form-id="libCity" class="span4  digits" >
					</div>
		  		<div class="control-group">
		    		<label for="libCity_longitude"><b>Longitude</b></label>
						<input id="libCity_longitude" name="longitude" type="text"
							form-id="libCity" class="span4  digits" >
					</div>
				<input type="hidden" id="libCity_id" name="id" form-id="libCity">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibCity: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libCityForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libCity", "libCity", "api/data/" + mode,
			  	"LibCityGrid", theme + "/lib-city-grid",
					false, true, false, {});
		  }
		});
	});
</script>