<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"PoleLengthGrid",
		"pole-length-grid",
		$this->result["PoleLength"]["Paging"]["CurrentPage"],
		$this->result["PoleLength"]["Paging"]["TotalPages"],
		$this->result["PoleLength"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["PoleLength"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "pole_length.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('poleLength', 'pole_length.name', 'asc');"></i>
							<i class="icon-<?php echo "pole_length.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('poleLength', 'pole_length.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "pole_length.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('poleLength', 'pole_length.created', 'asc');"></i>
							<i class="icon-<?php echo "pole_length.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('poleLength', 'pole_length.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "pole_length.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('poleLength', 'pole_length.updated', 'asc');"></i>
							<i class="icon-<?php echo "pole_length.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('poleLength', 'pole_length.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addPoleLength();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_poleLength_pole_length.name" type="text" class="span12 srch-poleLength"
						value="<?php echo isset($this->result['PoleLength']['Search']['pole_length.name']) ? $this->result['PoleLength']['Search']['pole_length.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_poleLength_pole_length.created" type="text" class="span12 srch-poleLength"
						value="<?php echo isset($this->result['PoleLength']['Search']['pole_length.created']) ? $this->result['PoleLength']['Search']['pole_length.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_poleLength_pole_length.updated" type="text" class="span12 srch-poleLength"
						value="<?php echo isset($this->result['PoleLength']['Search']['pole_length.updated']) ? $this->result['PoleLength']['Search']['pole_length.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-poleLength');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["PoleLength"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["pole_length_name"]; ?></td>
					<td><?php echo $record["pole_length_created"]; ?></td>
					<td><?php echo $record["pole_length_updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editPoleLength(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["PoleLength"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var poleLengthData = <?php echo Zend_Json::encode($this->data["PoleLength"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-poleLength"]();
		});
		$(".srch-poleLength").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-poleLength"]();
		    }
		});
	});
	
</script>