<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibCurrencyGrid",
		"lib-currency-grid",
		$this->result["LibCurrency"]["Paging"]["CurrentPage"],
		$this->result["LibCurrency"]["Paging"]["TotalPages"],
		$this->result["LibCurrency"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibCurrency"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Prefix</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_currency.prefix" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCurrency', 'lib_currency.prefix', 'asc');"></i>
							<i class="icon-<?php echo "lib_currency.prefix" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCurrency', 'lib_currency.prefix', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Code</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_currency.code" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCurrency', 'lib_currency.code', 'asc');"></i>
							<i class="icon-<?php echo "lib_currency.code" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCurrency', 'lib_currency.code', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_currency.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libCurrency', 'lib_currency.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_currency.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libCurrency', 'lib_currency.name', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibCurrency();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCurrency_lib_currency.prefix" type="text" class="span12 srch-libCurrency"
						value="<?php echo isset($this->result['LibCurrency']['Search']['lib_currency.prefix']) ? $this->result['LibCurrency']['Search']['lib_currency.prefix'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCurrency_lib_currency.code" type="text" class="span12 srch-libCurrency"
						value="<?php echo isset($this->result['LibCurrency']['Search']['lib_currency.code']) ? $this->result['LibCurrency']['Search']['lib_currency.code'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libCurrency_lib_currency.name" type="text" class="span12 srch-libCurrency"
						value="<?php echo isset($this->result['LibCurrency']['Search']['lib_currency.name']) ? $this->result['LibCurrency']['Search']['lib_currency.name'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libCurrency');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibCurrency"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["prefix"]; ?></td>
					<td><?php echo $record["code"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibCurrency(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibCurrency"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libCurrencyData = <?php echo Zend_Json::encode($this->data["LibCurrency"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libCurrency"]();
		});
		$(".srch-libCurrency").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libCurrency"]();
		    }
		});
	});
	
</script>