<!-- LibCurrency: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibCurrency">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libCurrencyModalHeading">Edit Lib Currency</h3>
	  </div>
		<form id="libCurrencyForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libCurrency_prefix"><b>Prefix *</b></label>
						<input id="libCurrency_prefix" name="prefix" type="text"
							form-id="libCurrency" class="span4 required" maxlength="3">
					</div>
		  		<div class="control-group">
		    		<label for="libCurrency_code"><b>Code *</b></label>
						<input id="libCurrency_code" name="code" type="text"
							form-id="libCurrency" class="span4 required" maxlength="3">
					</div>
		  		<div class="control-group">
		    		<label for="libCurrency_name"><b>Name *</b></label>
						<input id="libCurrency_name" name="name" type="text"
							form-id="libCurrency" class="span12 required" maxlength="50">
					</div>
				<input type="hidden" id="libCurrency_id" name="id" form-id="libCurrency">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibCurrency: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libCurrencyForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libCurrency", "libCurrency", "api/data/" + mode,
			  	"LibCurrencyGrid", theme + "/lib-currency-grid",
					false, true, false, {});
		  }
		});
	});
</script>