
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- LibVideo: Data Grid -->
<span id="LibVideoGrid">
<?php include_once("lib-video-grid.phtml");?>
</span>
<!-- [End] LibVideo: Data Grid -->

<!-- LibVideo: Modal Form -->
<?php include_once("lib-video-modal.phtml");?>
<!-- [End] LibVideo: Modal Form -->


<script type="text/javascript">

	var theme = "source/lib-video";

	$(document).ready(function() {
		$("#navLibVideo").addClass("active");
		searchHandler["srch-libVideo"] = {
				action: theme + "/lib-video-grid",
				container: "LibVideoGrid"
		};
    searchStack["srch-libVideo"] = wrapFunction(search, this, ["srch-libVideo"]);
	});

	function addLibVideo(id) {
		//$("#libVideoModalHeading").html("Add New Lib Video");
		mode = "create";
		clearForm("libVideo", "modalLibVideo");
	}

	function editLibVideo(id) {
		//$("#libVideoModalHeading").html("Edit Lib Video");
		mode = "update";
		populateForm("libVideo", "lib_video", libVideoData[id], "modalLibVideo");
	}

</script>