<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibVideoGrid",
		"lib-video-grid",
		$this->result["LibVideo"]["Paging"]["CurrentPage"],
		$this->result["LibVideo"]["Paging"]["TotalPages"],
		$this->result["LibVideo"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibVideo"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Video</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_video.video" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libVideo', 'lib_video.video', 'asc');"></i>
							<i class="icon-<?php echo "lib_video.video" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libVideo', 'lib_video.video', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mime Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_video.mime_type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libVideo', 'lib_video.mime_type', 'asc');"></i>
							<i class="icon-<?php echo "lib_video.mime_type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libVideo', 'lib_video.mime_type', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibVideo();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libVideo_lib_video.video" type="text" class="span12 srch-libVideo"
						value="<?php echo isset($this->result['LibVideo']['Search']['lib_video.video']) ? $this->result['LibVideo']['Search']['lib_video.video'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libVideo_lib_video.mime_type" type="text" class="span12 srch-libVideo"
						value="<?php echo isset($this->result['LibVideo']['Search']['lib_video.mime_type']) ? $this->result['LibVideo']['Search']['lib_video.mime_type'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libVideo');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibVideo"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["video"]; ?></td>
					<td><?php echo $record["mime_type"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibVideo(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibVideo"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="2">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libVideoData = <?php echo Zend_Json::encode($this->data["LibVideo"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libVideo"]();
		});
		$(".srch-libVideo").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libVideo"]();
		    }
		});
	});
	
</script>