<!-- LibVideo: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibVideo">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libVideoModalHeading">Edit Lib Video</h3>
	  </div>
		<form id="libVideoForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libVideo_mime_type"><b>Mime Type</b></label>
						<input id="libVideo_mime_type" name="mime_type" type="text"
							form-id="libVideo" class="span12 " maxlength="200">
					</div>
				<input type="hidden" id="libVideo_id" name="id" form-id="libVideo">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibVideo: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libVideoForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libVideo", "libVideo", "api/data/" + mode,
			  	"LibVideoGrid", theme + "/lib-video-grid",
					false, true, false, {});
		  }
		});
	});
</script>