
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- LibService: Data Grid -->
<span id="LibServiceGrid">
<?php include_once("lib-service-grid.phtml");?>
</span>
<!-- [End] LibService: Data Grid -->

<!-- LibService: Modal Form -->
<?php include_once("lib-service-modal.phtml");?>
<!-- [End] LibService: Modal Form -->


<script type="text/javascript">

	var theme = "source/lib-service";

	$(document).ready(function() {
		$("#navLibService").addClass("active");
		searchHandler["srch-libService"] = {
				action: theme + "/lib-service-grid",
				container: "LibServiceGrid"
		};
    searchStack["srch-libService"] = wrapFunction(search, this, ["srch-libService"]);
	});

	function addLibService(id) {
		//$("#libServiceModalHeading").html("Add New Lib Service");
		mode = "create";
		clearForm("libService", "modalLibService");
	}

	function editLibService(id) {
		//$("#libServiceModalHeading").html("Edit Lib Service");
		mode = "update";
		populateForm("libService", "lib_service", libServiceData[id], "modalLibService");
	}

</script>