<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibServiceGrid",
		"lib-service-grid",
		$this->result["LibService"]["Paging"]["CurrentPage"],
		$this->result["LibService"]["Paging"]["TotalPages"],
		$this->result["LibService"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibService"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_service.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libService', 'lib_service.name', 'asc');"></i>
							<i class="icon-<?php echo "lib_service.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libService', 'lib_service.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_service.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libService', 'lib_service.created', 'asc');"></i>
							<i class="icon-<?php echo "lib_service.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libService', 'lib_service.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_service.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libService', 'lib_service.updated', 'asc');"></i>
							<i class="icon-<?php echo "lib_service.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libService', 'lib_service.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibService();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libService_lib_service.name" type="text" class="span12 srch-libService"
						value="<?php echo isset($this->result['LibService']['Search']['lib_service.name']) ? $this->result['LibService']['Search']['lib_service.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libService_lib_service.created" type="text" class="span12 srch-libService"
						value="<?php echo isset($this->result['LibService']['Search']['lib_service.created']) ? $this->result['LibService']['Search']['lib_service.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libService_lib_service.updated" type="text" class="span12 srch-libService"
						value="<?php echo isset($this->result['LibService']['Search']['lib_service.updated']) ? $this->result['LibService']['Search']['lib_service.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libService');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibService"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibService(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibService"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libServiceData = <?php echo Zend_Json::encode($this->data["LibService"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libService"]();
		});
		$(".srch-libService").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libService"]();
		    }
		});
	});
	
</script>