<!-- LibService: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibService">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libServiceModalHeading">Edit Lib Service</h3>
	  </div>
		<form id="libServiceForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libService_name"><b>Name *</b></label>
						<input id="libService_name" name="name" type="text"
							form-id="libService" class="span12 required" maxlength="50">
					</div>
				<input type="hidden" id="libService_id" name="id" form-id="libService">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibService: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libServiceForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libService", "libService", "api/data/" + mode,
			  	"LibServiceGrid", theme + "/lib-service-grid",
					false, true, false, {});
		  }
		});
	});
</script>