<!-- LibRepeaterTemplate: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibRepeaterTemplate">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libRepeaterTemplateModalHeading">Edit Lib Repeater Template</h3>
	  </div>
		<form id="libRepeaterTemplateForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="libRepeaterTemplate_lib_template_id"><b>Lib Template *</b></label>
						<select id="libRepeaterTemplate_lib_template_id" name="lib_template_id"
							form-id="libRepeaterTemplate" class="span12 required" >
							<option value="">-- Select Lib Template * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listLibTemplate"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="libRepeaterTemplate_group_field"><b>Group Field</b></label>
						<input id="libRepeaterTemplate_group_field" name="group_field" type="text"
							form-id="libRepeaterTemplate" class="span12 " maxlength="50">
					</div>
		  		<div class="control-group">
			  		<label for="libRepeaterTemplate_group_repeater"><b>Group Repeater</b></label>
						<textarea id="libRepeaterTemplate_group_repeater" name="group_repeater" rows="5"
							form-id="libRepeaterTemplate" class="span12 " maxlength="65535"></textarea>
					</div>
		  		<div class="control-group">
			  		<label for="libRepeaterTemplate_row_repeater_odd"><b>Row Repeater Odd</b></label>
						<textarea id="libRepeaterTemplate_row_repeater_odd" name="row_repeater_odd" rows="5"
							form-id="libRepeaterTemplate" class="span12 " maxlength="65535"></textarea>
					</div>
		  		<div class="control-group">
			  		<label for="libRepeaterTemplate_row_repeater_even"><b>Row Repeater Even</b></label>
						<textarea id="libRepeaterTemplate_row_repeater_even" name="row_repeater_even" rows="5"
							form-id="libRepeaterTemplate" class="span12 " maxlength="65535"></textarea>
					</div>
				<input type="hidden" id="libRepeaterTemplate_id" name="id" form-id="libRepeaterTemplate">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibRepeaterTemplate: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libRepeaterTemplateForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libRepeaterTemplate", "libRepeaterTemplate", "api/data/" + mode,
			  	"LibRepeaterTemplateGrid", theme + "/lib-repeater-template-grid",
					false, true, false, {});
		  }
		});
	});
</script>