<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"TownGrid",
		"town-grid",
		$this->result["Town"]["Paging"]["CurrentPage"],
		$this->result["Town"]["Paging"]["TotalPages"],
		$this->result["Town"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Town"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Location</b>
						<div class="pull-right">
							<i class="icon-<?php echo "town.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('town', 'town.name', 'asc');"></i>
							<i class="icon-<?php echo "town.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('town', 'town.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "town.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('town', 'town.name', 'asc');"></i>
							<i class="icon-<?php echo "town.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('town', 'town.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "town.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('town', 'town.created', 'asc');"></i>
							<i class="icon-<?php echo "town.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('town', 'town.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "town.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('town', 'town.updated', 'asc');"></i>
							<i class="icon-<?php echo "town.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('town', 'town.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addTown();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_town_location.name" type="text" class="span12 srch-town"
						value="<?php echo isset($this->result['Town']['Search']['location.name']) ? $this->result['Town']['Search']['location.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_town_town.name" type="text" class="span12 srch-town"
						value="<?php echo isset($this->result['Town']['Search']['town.name']) ? $this->result['Town']['Search']['town.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_town_town.created" type="text" class="span12 srch-town"
						value="<?php echo isset($this->result['Town']['Search']['town.created']) ? $this->result['Town']['Search']['town.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_town_town.updated" type="text" class="span12 srch-town"
						value="<?php echo isset($this->result['Town']['Search']['town.updated']) ? $this->result['Town']['Search']['town.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-town');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Town"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["location_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editTown(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Town"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var townData = <?php echo Zend_Json::encode($this->data["Town"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-town"]();
		});
		$(".srch-town").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-town"]();
		    }
		});
	});
	
</script>