<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AppLinkRequestGrid",
		"app-link-request-grid",
		$this->result["AppLinkRequest"]["Paging"]["CurrentPage"],
		$this->result["AppLinkRequest"]["Paging"]["TotalPages"],
		$this->result["AppLinkRequest"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["AppLinkRequest"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Profile</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_link_request.first_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appLinkRequest', 'app_link_request.first_name', 'asc');"></i>
							<i class="icon-<?php echo "app_link_request.first_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appLinkRequest', 'app_link_request.first_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Device Os</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_link_request.device_os" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appLinkRequest', 'app_link_request.device_os', 'asc');"></i>
							<i class="icon-<?php echo "app_link_request.device_os" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appLinkRequest', 'app_link_request.device_os', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Device Cpu</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_link_request.device_cpu" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appLinkRequest', 'app_link_request.device_cpu', 'asc');"></i>
							<i class="icon-<?php echo "app_link_request.device_cpu" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appLinkRequest', 'app_link_request.device_cpu', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Ip Address</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_link_request.ip_address" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appLinkRequest', 'app_link_request.ip_address', 'asc');"></i>
							<i class="icon-<?php echo "app_link_request.ip_address" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appLinkRequest', 'app_link_request.ip_address', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Is Blacklisted</b>
						<div class="pull-right">
							<i class="icon-<?php echo "app_link_request.is_blacklisted" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('appLinkRequest', 'app_link_request.is_blacklisted', 'asc');"></i>
							<i class="icon-<?php echo "app_link_request.is_blacklisted" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('appLinkRequest', 'app_link_request.is_blacklisted', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAppLinkRequest();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appLinkRequest_profile.first_name" type="text" class="span12 srch-appLinkRequest"
						value="<?php echo isset($this->result['AppLinkRequest']['Search']['profile.first_name']) ? $this->result['AppLinkRequest']['Search']['profile.first_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appLinkRequest_app_link_request.device_os" type="text" class="span12 srch-appLinkRequest"
						value="<?php echo isset($this->result['AppLinkRequest']['Search']['app_link_request.device_os']) ? $this->result['AppLinkRequest']['Search']['app_link_request.device_os'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appLinkRequest_app_link_request.device_cpu" type="text" class="span12 srch-appLinkRequest"
						value="<?php echo isset($this->result['AppLinkRequest']['Search']['app_link_request.device_cpu']) ? $this->result['AppLinkRequest']['Search']['app_link_request.device_cpu'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appLinkRequest_app_link_request.ip_address" type="text" class="span12 srch-appLinkRequest"
						value="<?php echo isset($this->result['AppLinkRequest']['Search']['app_link_request.ip_address']) ? $this->result['AppLinkRequest']['Search']['app_link_request.ip_address'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_appLinkRequest_app_link_request.is_blacklisted" type="text" class="span12 srch-appLinkRequest"
						value="<?php echo isset($this->result['AppLinkRequest']['Search']['app_link_request.is_blacklisted']) ? $this->result['AppLinkRequest']['Search']['app_link_request.is_blacklisted'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-appLinkRequest');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["AppLinkRequest"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["profile_first_name"]; ?></td>
					<td><?php echo $record["device_os"]; ?></td>
					<td><?php echo $record["device_cpu"]; ?></td>
					<td><?php echo $record["ip_address"]; ?></td>
					<td><?php echo $record["is_blacklisted"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAppLinkRequest(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["AppLinkRequest"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var appLinkRequestData = <?php echo Zend_Json::encode($this->data["AppLinkRequest"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-appLinkRequest"]();
		});
		$(".srch-appLinkRequest").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-appLinkRequest"]();
		    }
		});
	});

</script>