
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- AppLinkRequest: Data Grid -->
<span id="AppLinkRequestGrid">
<?php include_once("app-link-request-grid.phtml");?>
</span>
<!-- [End] AppLinkRequest: Data Grid -->

<!-- AppLinkRequest: Modal Form -->
<?php include_once("app-link-request-modal.phtml");?>
<!-- [End] AppLinkRequest: Modal Form -->


<script type="text/javascript">

	var theme = "source/app-link-request";

	$(document).ready(function() {
		$("#navAppLinkRequest").addClass("active");
		searchHandler["srch-appLinkRequest"] = {
				action: theme + "/app-link-request-grid",
				container: "AppLinkRequestGrid"
		};
    searchStack["srch-appLinkRequest"] = wrapFunction(search, this, ["srch-appLinkRequest"]);
	});

	function addAppLinkRequest(id) {
		//$("#appLinkRequestModalHeading").html("Add New App Link Request");
		mode = "create";
		clearForm("appLinkRequest", "modalAppLinkRequest");
	}

	function editAppLinkRequest(id) {
		//$("#appLinkRequestModalHeading").html("Edit App Link Request");
		mode = "update";
		populateForm("appLinkRequest", "app_link_request", appLinkRequestData[id], "modalAppLinkRequest");
	}

</script>