<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ConditionGrid",
		"condition-grid",
		$this->result["Condition"]["Paging"]["CurrentPage"],
		$this->result["Condition"]["Paging"]["TotalPages"],
		$this->result["Condition"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Condition"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "condition.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('condition', 'condition.name', 'asc');"></i>
							<i class="icon-<?php echo "condition.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('condition', 'condition.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "condition.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('condition', 'condition.created', 'asc');"></i>
							<i class="icon-<?php echo "condition.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('condition', 'condition.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "condition.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('condition', 'condition.updated', 'asc');"></i>
							<i class="icon-<?php echo "condition.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('condition', 'condition.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addCondition();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_condition_condition.name" type="text" class="span12 srch-condition"
						value="<?php echo isset($this->result['Condition']['Search']['condition.name']) ? $this->result['Condition']['Search']['condition.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_condition_condition.created" type="text" class="span12 srch-condition"
						value="<?php echo isset($this->result['Condition']['Search']['condition.created']) ? $this->result['Condition']['Search']['condition.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_condition_condition.updated" type="text" class="span12 srch-condition"
						value="<?php echo isset($this->result['Condition']['Search']['condition.updated']) ? $this->result['Condition']['Search']['condition.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-condition');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Condition"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editCondition(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Condition"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var conditionData = <?php echo Zend_Json::encode($this->data["Condition"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-condition"]();
		});
		$(".srch-condition").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-condition"]();
		    }
		});
	});
	
</script>