<!-- Condition: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalCondition">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="conditionModalHeading">Edit Condition</h3>
	  </div>
		<form id="conditionForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="condition_name"><b>Name *</b></label>
						<input id="condition_name" name="name" type="text"
							form-id="condition" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="condition_id" name="id" form-id="condition">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] Condition: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#conditionForm").validate({
		  submitHandler: function(form) {
			  doUpdate("condition", "condition", "api/data/" + mode,
			  	"ConditionGrid", theme + "/condition-grid",
					false, true, false, {});
		  }
		});
	});
</script>