
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- Condition: Data Grid -->
<span id="ConditionGrid">
<?php include_once("condition-grid.phtml");?>
</span>
<!-- [End] Condition: Data Grid -->

<!-- Condition: Modal Form -->
<?php include_once("condition-modal.phtml");?>
<!-- [End] Condition: Modal Form -->


<script type="text/javascript">

	var theme = "source/condition";

	$(document).ready(function() {
		$("#navCondition").addClass("active");
		searchHandler["srch-condition"] = {
				action: theme + "/condition-grid",
				container: "ConditionGrid"
		};
    searchStack["srch-condition"] = wrapFunction(search, this, ["srch-condition"]);
	});

	function addCondition(id) {
		//$("#conditionModalHeading").html("Add New Condition");
		mode = "create";
		clearForm("condition", "modalCondition");
	}

	function editCondition(id) {
		//$("#conditionModalHeading").html("Edit Condition");
		mode = "update";
		populateForm("condition", "condition", conditionData[id], "modalCondition");
	}

</script>