<!-- Street: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalStreet">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="streetModalHeading">Edit Street</h3>
	  </div>
		<form id="streetForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="street_town_id"><b>Town *</b></label>
						<select id="street_town_id" name="town_id"
							form-id="street" class="span12 required" >
							<option value="">-- Select Town * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listTown"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="street_name"><b>Name *</b></label>
						<input id="street_name" name="name" type="text"
							form-id="street" class="span12 required" maxlength="100">
					</div>
				<input type="hidden" id="street_id" name="id" form-id="street">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] Street: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#streetForm").validate({
		  submitHandler: function(form) {
			  doUpdate("street", "street", "api/data/" + mode,
			  	"StreetGrid", theme + "/street-grid",
					false, true, false, {});
		  }
		});
	});
</script>