<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"StreetGrid",
		"street-grid",
		$this->result["Street"]["Paging"]["CurrentPage"],
		$this->result["Street"]["Paging"]["TotalPages"],
		$this->result["Street"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Street"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Town</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('street', 'street.name', 'asc');"></i>
							<i class="icon-<?php echo "street.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('street', 'street.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('street', 'street.name', 'asc');"></i>
							<i class="icon-<?php echo "street.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('street', 'street.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('street', 'street.created', 'asc');"></i>
							<i class="icon-<?php echo "street.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('street', 'street.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "street.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('street', 'street.updated', 'asc');"></i>
							<i class="icon-<?php echo "street.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('street', 'street.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addStreet();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_street_town.name" type="text" class="span12 srch-street"
						value="<?php echo isset($this->result['Street']['Search']['town.name']) ? $this->result['Street']['Search']['town.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_street_street.name" type="text" class="span12 srch-street"
						value="<?php echo isset($this->result['Street']['Search']['street.name']) ? $this->result['Street']['Search']['street.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_street_street.created" type="text" class="span12 srch-street"
						value="<?php echo isset($this->result['Street']['Search']['street.created']) ? $this->result['Street']['Search']['street.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_street_street.updated" type="text" class="span12 srch-street"
						value="<?php echo isset($this->result['Street']['Search']['street.updated']) ? $this->result['Street']['Search']['street.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-street');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Street"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["town_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editStreet(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Street"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var streetData = <?php echo Zend_Json::encode($this->data["Street"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-street"]();
		});
		$(".srch-street").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-street"]();
		    }
		});
	});
	
</script>