<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"FloorGrid",
		"floor-grid",
		$this->result["Floor"]["Paging"]["CurrentPage"],
		$this->result["Floor"]["Paging"]["TotalPages"],
		$this->result["Floor"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Floor"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Building</b>
						<div class="pull-right">
							<i class="icon-<?php echo "floor.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('floor', 'floor.name', 'asc');"></i>
							<i class="icon-<?php echo "floor.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('floor', 'floor.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "floor.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('floor', 'floor.name', 'asc');"></i>
							<i class="icon-<?php echo "floor.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('floor', 'floor.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "floor.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('floor', 'floor.created', 'asc');"></i>
							<i class="icon-<?php echo "floor.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('floor', 'floor.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "floor.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('floor', 'floor.updated', 'asc');"></i>
							<i class="icon-<?php echo "floor.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('floor', 'floor.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addFloor();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_floor_building.name" type="text" class="span12 srch-floor"
						value="<?php echo isset($this->result['Floor']['Search']['building.name']) ? $this->result['Floor']['Search']['building.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_floor_floor.name" type="text" class="span12 srch-floor"
						value="<?php echo isset($this->result['Floor']['Search']['floor.name']) ? $this->result['Floor']['Search']['floor.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_floor_floor.created" type="text" class="span12 srch-floor"
						value="<?php echo isset($this->result['Floor']['Search']['floor.created']) ? $this->result['Floor']['Search']['floor.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_floor_floor.updated" type="text" class="span12 srch-floor"
						value="<?php echo isset($this->result['Floor']['Search']['floor.updated']) ? $this->result['Floor']['Search']['floor.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-floor');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Floor"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["building_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editFloor(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Floor"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var floorData = <?php echo Zend_Json::encode($this->data["Floor"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-floor"]();
		});
		$(".srch-floor").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-floor"]();
		    }
		});
	});
	
</script>