
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- Floor: Data Grid -->
<span id="FloorGrid">
<?php include_once("floor-grid.phtml");?>
</span>
<!-- [End] Floor: Data Grid -->

<!-- Floor: Modal Form -->
<?php include_once("floor-modal.phtml");?>
<!-- [End] Floor: Modal Form -->


<script type="text/javascript">

	var theme = "source/floor";

	$(document).ready(function() {
		$("#navFloor").addClass("active");
		searchHandler["srch-floor"] = {
				action: theme + "/floor-grid",
				container: "FloorGrid"
		};
    searchStack["srch-floor"] = wrapFunction(search, this, ["srch-floor"]);
	});

	function addFloor(id) {
		//$("#floorModalHeading").html("Add New Floor");
		mode = "create";
		clearForm("floor", "modalFloor");
	}

	function editFloor(id) {
		//$("#floorModalHeading").html("Edit Floor");
		mode = "update";
		populateForm("floor", "floor", floorData[id], "modalFloor");
	}

</script>