<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"BillInvoiceGrid",
		"bill-invoice-grid",
		$this->result["BillInvoice"]["Paging"]["CurrentPage"],
		$this->result["BillInvoice"]["Paging"]["TotalPages"],
		$this->result["BillInvoice"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["BillInvoice"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Invoice Nr</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice.invoice_nr" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoice', 'bill_invoice.invoice_nr', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice.invoice_nr" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoice', 'bill_invoice.invoice_nr', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice.type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoice', 'bill_invoice.type', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice.type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoice', 'bill_invoice.type', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Profile</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice.first_name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoice', 'bill_invoice.first_name', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice.first_name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoice', 'bill_invoice.first_name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Lib Currency</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice.prefix" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoice', 'bill_invoice.prefix', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice.prefix" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoice', 'bill_invoice.prefix', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Vat</b>
						<div class="pull-right">
							<i class="icon-<?php echo "bill_invoice.vat" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('billInvoice', 'bill_invoice.vat', 'asc');"></i>
							<i class="icon-<?php echo "bill_invoice.vat" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('billInvoice', 'bill_invoice.vat', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addBillInvoice();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoice_bill_invoice.invoice_nr" type="text" class="span12 srch-billInvoice"
						value="<?php echo isset($this->result['BillInvoice']['Search']['bill_invoice.invoice_nr']) ? $this->result['BillInvoice']['Search']['bill_invoice.invoice_nr'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoice_bill_invoice.type" type="text" class="span12 srch-billInvoice"
						value="<?php echo isset($this->result['BillInvoice']['Search']['bill_invoice.type']) ? $this->result['BillInvoice']['Search']['bill_invoice.type'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoice_profile.first_name" type="text" class="span12 srch-billInvoice"
						value="<?php echo isset($this->result['BillInvoice']['Search']['profile.first_name']) ? $this->result['BillInvoice']['Search']['profile.first_name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoice_lib_currency.prefix" type="text" class="span12 srch-billInvoice"
						value="<?php echo isset($this->result['BillInvoice']['Search']['lib_currency.prefix']) ? $this->result['BillInvoice']['Search']['lib_currency.prefix'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_billInvoice_bill_invoice.vat" type="text" class="span12 srch-billInvoice"
						value="<?php echo isset($this->result['BillInvoice']['Search']['bill_invoice.vat']) ? $this->result['BillInvoice']['Search']['bill_invoice.vat'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-billInvoice');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["BillInvoice"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["invoice_nr"]; ?></td>
					<td><?php echo $record["type"]; ?></td>
					<td><?php echo $record["profile_first_name"]; ?></td>
					<td><?php echo $record["lib_currency_prefix"]; ?></td>
					<td><?php echo $record["vat"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editBillInvoice(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["BillInvoice"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var billInvoiceData = <?php echo Zend_Json::encode($this->data["BillInvoice"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-billInvoice"]();
		});
		$(".srch-billInvoice").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-billInvoice"]();
		    }
		});
	});
	
</script>