
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- BillInvoice: Data Grid -->
<span id="BillInvoiceGrid">
<?php include_once("bill-invoice-grid.phtml");?>
</span>
<!-- [End] BillInvoice: Data Grid -->

<!-- BillInvoice: Modal Form -->
<?php include_once("bill-invoice-modal.phtml");?>
<!-- [End] BillInvoice: Modal Form -->


<script type="text/javascript">

	var theme = "source/bill-invoice";

	$(document).ready(function() {
		$("#navBillInvoice").addClass("active");
		searchHandler["srch-billInvoice"] = {
				action: theme + "/bill-invoice-grid",
				container: "BillInvoiceGrid"
		};
    searchStack["srch-billInvoice"] = wrapFunction(search, this, ["srch-billInvoice"]);
	});

	function addBillInvoice(id) {
		//$("#billInvoiceModalHeading").html("Add New Bill Invoice");
		mode = "create";
		clearForm("billInvoice", "modalBillInvoice");
	}

	function editBillInvoice(id) {
		//$("#billInvoiceModalHeading").html("Edit Bill Invoice");
		mode = "update";
		populateForm("billInvoice", "bill_invoice", billInvoiceData[id], "modalBillInvoice");
	}

</script>