<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibNotificationLogGrid",
		"lib-notification-log-grid",
		$this->result["LibNotificationLog"]["Paging"]["CurrentPage"],
		$this->result["LibNotificationLog"]["Paging"]["TotalPages"],
		$this->result["LibNotificationLog"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibNotificationLog"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Email To</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_notification_log.email_to" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNotificationLog', 'lib_notification_log.email_to', 'asc');"></i>
							<i class="icon-<?php echo "lib_notification_log.email_to" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNotificationLog', 'lib_notification_log.email_to', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Email Subject</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_notification_log.email_subject" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNotificationLog', 'lib_notification_log.email_subject', 'asc');"></i>
							<i class="icon-<?php echo "lib_notification_log.email_subject" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNotificationLog', 'lib_notification_log.email_subject', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Sms To</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_notification_log.sms_to" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNotificationLog', 'lib_notification_log.sms_to', 'asc');"></i>
							<i class="icon-<?php echo "lib_notification_log.sms_to" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNotificationLog', 'lib_notification_log.sms_to', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Sms Status</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_notification_log.sms_status" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNotificationLog', 'lib_notification_log.sms_status', 'asc');"></i>
							<i class="icon-<?php echo "lib_notification_log.sms_status" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNotificationLog', 'lib_notification_log.sms_status', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_notification_log.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libNotificationLog', 'lib_notification_log.created', 'asc');"></i>
							<i class="icon-<?php echo "lib_notification_log.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libNotificationLog', 'lib_notification_log.created', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibNotificationLog();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libNotificationLog_lib_notification_log.email_to" type="text" class="span12 srch-libNotificationLog"
						value="<?php echo isset($this->result['LibNotificationLog']['Search']['lib_notification_log.email_to']) ? $this->result['LibNotificationLog']['Search']['lib_notification_log.email_to'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libNotificationLog_lib_notification_log.email_subject" type="text" class="span12 srch-libNotificationLog"
						value="<?php echo isset($this->result['LibNotificationLog']['Search']['lib_notification_log.email_subject']) ? $this->result['LibNotificationLog']['Search']['lib_notification_log.email_subject'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libNotificationLog_lib_notification_log.sms_to" type="text" class="span12 srch-libNotificationLog"
						value="<?php echo isset($this->result['LibNotificationLog']['Search']['lib_notification_log.sms_to']) ? $this->result['LibNotificationLog']['Search']['lib_notification_log.sms_to'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libNotificationLog_lib_notification_log.sms_status" type="text" class="span12 srch-libNotificationLog"
						value="<?php echo isset($this->result['LibNotificationLog']['Search']['lib_notification_log.sms_status']) ? $this->result['LibNotificationLog']['Search']['lib_notification_log.sms_status'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_libNotificationLog_lib_notification_log.created" type="text" class="span12 srch-libNotificationLog"
						value="<?php echo isset($this->result['LibNotificationLog']['Search']['lib_notification_log.created']) ? $this->result['LibNotificationLog']['Search']['lib_notification_log.created'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libNotificationLog');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibNotificationLog"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["email_to"]; ?></td>
					<td><?php echo $record["email_subject"]; ?></td>
					<td><?php echo $record["sms_to"]; ?></td>
					<td><?php echo $record["sms_status"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibNotificationLog(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibNotificationLog"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libNotificationLogData = <?php echo Zend_Json::encode($this->data["LibNotificationLog"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libNotificationLog"]();
		});
		$(".srch-libNotificationLog").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libNotificationLog"]();
		    }
		});
	});

</script>