<!-- LibDocument: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalLibDocument">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="libDocumentModalHeading">Edit Lib Document</h3>
	  </div>
		<form id="libDocumentForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="libDocument_mime_type"><b>Mime Type</b></label>
						<input id="libDocument_mime_type" name="mime_type" type="text"
							form-id="libDocument" class="span12 " maxlength="200">
					</div>
				<input type="hidden" id="libDocument_id" name="id" form-id="libDocument">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] LibDocument: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#libDocumentForm").validate({
		  submitHandler: function(form) {
			  doUpdate("libDocument", "libDocument", "api/data/" + mode,
			  	"LibDocumentGrid", theme + "/lib-document-grid",
					false, true, false, {});
		  }
		});
	});
</script>