<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LibDocumentGrid",
		"lib-document-grid",
		$this->result["LibDocument"]["Paging"]["CurrentPage"],
		$this->result["LibDocument"]["Paging"]["TotalPages"],
		$this->result["LibDocument"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["LibDocument"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Document</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_document.document" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libDocument', 'lib_document.document', 'asc');"></i>
							<i class="icon-<?php echo "lib_document.document" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libDocument', 'lib_document.document', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Mime Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "lib_document.mime_type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('libDocument', 'lib_document.mime_type', 'asc');"></i>
							<i class="icon-<?php echo "lib_document.mime_type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('libDocument', 'lib_document.mime_type', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLibDocument();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libDocument_lib_document.document" type="text" class="span12 srch-libDocument"
						value="<?php echo isset($this->result['LibDocument']['Search']['lib_document.document']) ? $this->result['LibDocument']['Search']['lib_document.document'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_libDocument_lib_document.mime_type" type="text" class="span12 srch-libDocument"
						value="<?php echo isset($this->result['LibDocument']['Search']['lib_document.mime_type']) ? $this->result['LibDocument']['Search']['lib_document.mime_type'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-libDocument');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["LibDocument"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["document"]; ?></td>
					<td><?php echo $record["mime_type"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLibDocument(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["LibDocument"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="2">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var libDocumentData = <?php echo Zend_Json::encode($this->data["LibDocument"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-libDocument"]();
		});
		$(".srch-libDocument").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-libDocument"]();
		    }
		});
	});
	
</script>