<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AssetGrid",
		"asset-grid",
		$this->result["Asset"]["Paging"]["CurrentPage"],
		$this->result["Asset"]["Paging"]["TotalPages"],
		$this->result["Asset"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Asset"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Item</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Surname</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.surname" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.surname', 'asc');"></i>
							<i class="icon-<?php echo "asset.surname" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.surname', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Email</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.email" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.email', 'asc');"></i>
							<i class="icon-<?php echo "asset.email" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.email', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Cell</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.cell" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.cell', 'asc');"></i>
							<i class="icon-<?php echo "asset.cell" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.cell', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAsset();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_item.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['item.name']) ? $this->result['Asset']['Search']['item.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_asset.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['asset.name']) ? $this->result['Asset']['Search']['asset.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_asset.surname" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['asset.surname']) ? $this->result['Asset']['Search']['asset.surname'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_asset.email" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['asset.email']) ? $this->result['Asset']['Search']['asset.email'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_asset.cell" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['asset.cell']) ? $this->result['Asset']['Search']['asset.cell'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-asset');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Asset"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["item_name"]; ?></td>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["surname"]; ?></td>
					<td><?php echo $record["email"]; ?></td>
					<td><?php echo $record["cell"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAsset(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Asset"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var assetData = <?php echo Zend_Json::encode($this->data["Asset"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-asset"]();
		});
		$(".srch-asset").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-asset"]();
		    }
		});
	});

</script>