<!-- Asset: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalAsset">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="assetModalHeading">Edit Asset</h3>
	  </div>
		<form id="assetForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
				  	<label for="asset_item_id"><b>Item *</b></label>
						<select id="asset_item_id" name="item_id"
							form-id="asset" class="span12 required" >
							<option value="">-- Select Item * --</option>
							<?php echo $utilDisplay->buildDropdownOptions($this->data["listItem"], false); ?>

						</select>
					</div>
		  		<div class="control-group">
		    		<label for="asset_name"><b>Name</b></label>
						<input id="asset_name" name="name" type="text"
							form-id="asset" class="span12 " maxlength="250">
					</div>
		  		<div class="control-group">
		    		<label for="asset_surname"><b>Surname</b></label>
						<input id="asset_surname" name="surname" type="text"
							form-id="asset" class="span12 " maxlength="250">
					</div>
		  		<div class="control-group">
		    		<label for="asset_email"><b>Email</b></label>
						<input id="asset_email" name="email" type="text"
							form-id="asset" class="span12 " maxlength="250">
					</div>
		  		<div class="control-group">
		    		<label for="asset_cell"><b>Cell</b></label>
						<input id="asset_cell" name="cell" type="text"
							form-id="asset" class="span8 " maxlength="20">
					</div>
				<input type="hidden" id="asset_id" name="id" form-id="asset">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] Asset: Modal Form -->
<script type="text/javascript">
	$(document).ready(function() {
		$("#assetForm").validate({
		  submitHandler: function(form) {
			  doUpdate("asset", "asset", "api/data/" + mode,
			  	"AssetGrid", theme + "/asset-grid",
					false, true, false, {});
		  }
		});
	});
</script>