
<?php
$utilDisplay = new Struct_Util_Display();
?>

<!-- AssetType: Data Grid -->
<span id="AssetTypeGrid">
<?php include_once("asset-type-grid.phtml");?>
</span>
<!-- [End] AssetType: Data Grid -->

<!-- AssetType: Modal Form -->
<?php include_once("asset-type-modal.phtml");?>
<!-- [End] AssetType: Modal Form -->


<script type="text/javascript">

	var theme = "source/asset-type";

	$(document).ready(function() {
		$("#navAssetType").addClass("active");
		searchHandler["srch-assetType"] = {
				action: theme + "/asset-type-grid",
				container: "AssetTypeGrid"
		};
    searchStack["srch-assetType"] = wrapFunction(search, this, ["srch-assetType"]);
	});

	function addAssetType(id) {
		//$("#assetTypeModalHeading").html("Add New Asset Type");
		mode = "create";
		clearForm("assetType", "modalAssetType");
	}

	function editAssetType(id) {
		//$("#assetTypeModalHeading").html("Edit Asset Type");
		mode = "update";
		populateForm("assetType", "asset_type", assetTypeData[id], "modalAssetType");
	}

</script>