<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"LocationGrid",
		"location-grid",
		$this->result["Location"]["Paging"]["CurrentPage"],
		$this->result["Location"]["Paging"]["TotalPages"],
		$this->result["Location"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Location"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "location.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('location', 'location.name', 'asc');"></i>
							<i class="icon-<?php echo "location.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('location', 'location.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "location.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('location', 'location.created', 'asc');"></i>
							<i class="icon-<?php echo "location.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('location', 'location.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "location.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('location', 'location.updated', 'asc');"></i>
							<i class="icon-<?php echo "location.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('location', 'location.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addLocation();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_location_location.name" type="text" class="span12 srch-location"
						value="<?php echo isset($this->result['Location']['Search']['location.name']) ? $this->result['Location']['Search']['location.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_location_location.created" type="text" class="span12 srch-location"
						value="<?php echo isset($this->result['Location']['Search']['location.created']) ? $this->result['Location']['Search']['location.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_location_location.updated" type="text" class="span12 srch-location"
						value="<?php echo isset($this->result['Location']['Search']['location.updated']) ? $this->result['Location']['Search']['location.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-location');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Location"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editLocation(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Location"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var locationData = <?php echo Zend_Json::encode($this->data["Location"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-location"]();
		});
		$(".srch-location").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-location"]();
		    }
		});
	});
	
</script>